import type { Metadata } from "next";
import Image from "next/image";
import { Search, SlidersHorizontal, TentTree } from "lucide-react";
import { CampingCard } from "@/components/camping-card";
import { CAMPING_FEATURES, CAMPING_TYPES } from "@/lib/camping-options";
import { getPlaceFilterOptions, getPlaces } from "@/lib/camping";
import { getDirection, resolveLocale } from "@/lib/i18n";
import { buildPageMetadata } from "@/lib/seo";
export const revalidate = 60;
export const metadata: Metadata = buildPageMetadata({ title: "Premium Camping Directory in Morocco", description: "Discover curated camping, glamping, caravan and outdoor stays across Morocco.", path: "/camping", image: "/images/camping.jpg" });
export default async function Page({ searchParams }: { searchParams: Promise<any> }) {
  const p = await searchParams; const locale = resolveLocale(p.lang); const filters = { q: p.q || "", location: p.location || "", category: p.category || "", type: p.type || "", feature: p.feature || "", sort: p.sort || "newest" };
  const [places, options, featured] = await Promise.all([getPlaces(filters), getPlaceFilterOptions(), getPlaces({ featured: true, limit: 4 })]);
  const select = (name: string, label: string, values: string[]) => <select name={name} defaultValue={filters[name as keyof typeof filters]} className="min-w-0 rounded-[1.15rem] border border-ink/10 bg-sand/30 px-4 py-3.5 text-sm font-semibold outline-none focus:border-clay focus:bg-white"><option value="">{label}</option>{values.map((value) => <option key={value}>{value}</option>)}</select>;
  return <main dir={getDirection(locale)} className="page-shell max-w-[1440px] space-y-14 pb-24 sm:space-y-20"><section className="relative min-h-[620px] overflow-hidden rounded-[2.5rem] bg-emerald-950 shadow-[0_35px_100px_rgba(15,61,46,.28)] sm:rounded-[3rem]"><Image src="/images/camping.jpg" alt="Camping Morocco" fill priority sizes="100vw" className="object-cover object-[center_58%]" /><div className="absolute inset-0 bg-[linear-gradient(112deg,rgba(3,20,14,.97),rgba(15,61,46,.78)_60%,rgba(249,115,22,.28))]" /><div className="relative flex min-h-[620px] items-end px-6 py-10 sm:px-10 sm:py-14 lg:px-16 lg:py-16"><div className="max-w-4xl text-white"><p className="inline-flex rounded-full border border-white/15 bg-white/10 px-4 py-2 text-xs font-black uppercase tracking-[.28em] backdrop-blur">Affiliate Camping Directory</p><h1 className="mt-6 text-4xl font-black leading-[1.03] tracking-[-.04em] sm:text-6xl lg:text-7xl">Premium camping places across Morocco</h1><p className="mt-6 max-w-3xl text-base leading-8 text-white/78 sm:text-lg">Curated camps, glamping stays, caravan parks, and outdoor escapes with direct partner access.</p><div className="mt-8 flex flex-wrap gap-3 text-xs font-bold text-white/85"><span className="rounded-full bg-white/10 px-4 py-2 backdrop-blur">Immersive outdoor stays</span><span className="rounded-full bg-white/10 px-4 py-2 backdrop-blur">Trusted partner access</span><span className="rounded-full bg-white/10 px-4 py-2 backdrop-blur">Across Morocco</span></div></div></div></section>
  {featured.length ? <section className="rounded-[2.75rem] bg-[linear-gradient(145deg,#edf7f2,#ffffff_58%,#fff4e8)] p-5 shadow-[0_30px_90px_rgba(15,61,46,.11)] sm:p-9 lg:p-12"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-black uppercase tracking-[.25em] text-clay">Hand-picked escapes</p><h2 className="mt-3 text-3xl font-black tracking-[-.03em] text-ink sm:text-5xl">Featured Camping Places</h2></div><p className="max-w-lg text-sm leading-7 text-ink/55">Outdoor stays selected for atmosphere, location, and memorable experiences.</p></div><div className="mt-9 grid gap-7 md:grid-cols-2 xl:grid-cols-3">{featured.map((place) => <CampingCard key={place._id} place={place} locale={locale} />)}</div></section> : null}
  <section className="sticky top-3 z-20 rounded-[2rem] border border-white/80 bg-white/95 p-4 shadow-[0_20px_60px_rgba(15,61,46,.13)] backdrop-blur-xl sm:p-5"><div className="mb-4 flex items-center justify-between gap-4"><div className="flex items-center gap-3"><span className="rounded-full bg-emerald-50 p-2.5 text-forest"><SlidersHorizontal className="h-5 w-5" /></span><div><h2 className="font-black text-ink">Find your camping escape</h2><p className="text-xs text-ink/45">{places.length} places available</p></div></div></div><form className="grid gap-3 md:grid-cols-2 xl:grid-cols-[1.5fr_repeat(5,minmax(0,1fr))_auto]"><input type="hidden" name="lang" value={locale} /><label className="relative md:col-span-2 xl:col-span-1"><Search className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-ink/40" /><input name="q" defaultValue={filters.q} placeholder="Search by camping name" className="w-full rounded-[1.15rem] border border-ink/10 bg-sand/30 py-3.5 pl-11 pr-4 text-sm outline-none focus:border-clay focus:bg-white" /></label>{select("location", "All locations", options.locations)}{select("category", "All categories", options.categories)}{select("type", "All types", [...CAMPING_TYPES])}{select("feature", "All features", [...CAMPING_FEATURES])}<select name="sort" defaultValue={filters.sort} className="rounded-[1.15rem] border border-ink/10 bg-sand/30 px-4 py-3.5 text-sm font-semibold"><option value="newest">Newest</option><option value="popular">Popularity</option><option value="featured">Featured first</option></select><button className="rounded-[1.15rem] bg-forest px-6 py-3.5 text-sm font-black text-white shadow-[0_12px_28px_rgba(15,61,46,.2)] transition hover:bg-clay">Explore</button></form></section>
  <section className="space-y-8"><div><p className="text-xs font-black uppercase tracking-[.25em] text-clay">Camping directory</p><h2 className="mt-3 text-3xl font-black tracking-[-.03em] text-ink sm:text-5xl">Find a place worth staying for</h2></div>{places.length ? <div className="grid gap-8 md:grid-cols-2 xl:grid-cols-3">{places.map((place) => <CampingCard key={place._id} place={place} locale={locale} />)}</div> : <div className="rounded-[2.5rem] border border-dashed border-ink/15 bg-white p-12 text-center shadow-card"><TentTree className="mx-auto h-16 w-16 text-clay/60" /><h2 className="mt-4 text-2xl font-black">No camping places match these filters</h2></div>}</section></main>;
}
