import Link from "next/link";
import { notFound } from "next/navigation";
import { getAdminPageSession } from "@/lib/admin";
import { connectToDatabase } from "@/lib/db";
import ResellingProduct from "@/models/ResellingProduct";
import MarketplaceSyncLog from "@/models/MarketplaceSyncLog";
import { serializeDocument } from "@/lib/utils";
export const dynamic="force-dynamic";
export default async function MarketplaceSyncHistoryPage({params}:{params:Promise<{id:string}>}){await getAdminPageSession();await connectToDatabase();const{id}=await params;const product=await ResellingProduct.findById(id).lean();if(!product)notFound();const logs=serializeDocument(await MarketplaceSyncLog.find({productId:id}).sort({timestamp:-1}).limit(100).lean()) as any[];return <main className="page-shell space-y-6 pb-20"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.25em] text-clay">Source synchronization</p><h1 className="mt-2 text-3xl font-black">{product.title?.en||product.title?.fr||product.title?.ar}</h1><p className="mt-2 text-sm text-ink/60">{product.sourceSync?.supplier} · {product.sourceSync?.sourceUrl}</p></div><Link href="/admin/marketplace/products" className="rounded-full border border-ink/10 px-4 py-2 text-sm font-black">Back to products</Link></div><section className="overflow-hidden rounded-[2rem] bg-white shadow-card"><div className="grid grid-cols-[140px_120px_1fr_100px] gap-4 border-b border-ink/10 bg-sand/40 px-5 py-4 text-xs font-black uppercase tracking-wider"><span>Status</span><span>Date</span><span>Changes</span><span>Duration</span></div>{logs.length===0?<div className="p-6 text-sm text-ink/60">No synchronization history yet.</div>:logs.map(log=><div key={log._id} className="grid grid-cols-[140px_120px_1fr_100px] gap-4 border-b border-ink/5 px-5 py-4 text-sm"><span className="font-black">{log.status}</span><span className="text-ink/60">{new Date(log.timestamp).toLocaleString()}</span><div className="space-y-1">{log.changes?.length?log.changes.map((change:any)=><div key={change.field}><b>{change.field}</b>: {JSON.stringify(change.oldValue)} → {JSON.stringify(change.newValue)}</div>):<span className="text-ink/50">{log.error||"No fields changed."}</span>}</div><span className="text-ink/60">{log.durationMs} ms</span></div>)}</section></main>}
