import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import DestinationGallery from "@/components/destination-gallery";
import { getDestinationBySlug } from "@/lib/destinations";
import { getDirection, localizeField, resolveLocale, withLocale } from "@/lib/i18n";
import { buildPageMetadata } from "@/lib/seo";

export const revalidate = 60;

export async function generateMetadata({ params, searchParams }: { params: Promise<{ slug: string }>; searchParams: Promise<{ lang?: string }> }): Promise<Metadata> {
  const { slug } = await params; const { lang } = await searchParams; const locale = resolveLocale(lang); const item: any = await getDestinationBySlug(slug);
  if (!item) return { title: "Destination not found | Moroccan Trip" };
  return buildPageMetadata({ title: localizeField(item.seoTitle, locale) || `${localizeField(item.name, locale)} | Moroccan Trip`, description: localizeField(item.seoDescription, locale) || localizeField(item.shortDescription, locale), path: `/destinations/${slug}`, image: item.coverImage });
}

const copy = { ar: { all: "كل الوجهات", gallery: "معرض الصور", agencies: "وكالات مقترحة", book: "احجز الآن", contact: "تواصل", tip: "نصيحة سفر" }, fr: { all: "Toutes les destinations", gallery: "Galerie", agencies: "Agences recommandées", book: "Réserver", contact: "Contacter", tip: "Conseil voyage" }, en: { all: "All destinations", gallery: "Gallery", agencies: "Recommended agencies", book: "Book now", contact: "Contact", tip: "Travel tip" } } as const;

export default async function DestinationPage({ params, searchParams }: { params: Promise<{ slug: string }>; searchParams: Promise<{ lang?: string }> }) {
  const { slug } = await params; const { lang } = await searchParams; const locale = resolveLocale(lang); const t = copy[locale]; const item: any = await getDestinationBySlug(slug);
  if (!item) return <main className="page-shell py-24 text-center"><h1 className="text-4xl font-black">Destination not found</h1></main>;
  const name = localizeField(item.name, locale); const location = localizeField(item.location, locale); const article = Array.isArray(item.article) ? item.article : [];
  return <main dir={getDirection(locale)} className="page-shell max-w-[1320px] pb-24"><Link href={withLocale("/destinations", locale)} className="mb-6 inline-block text-sm font-black text-ink/55">← {t.all}</Link>
    <article><header className="relative min-h-[560px] overflow-hidden rounded-[2.75rem] bg-forest"><Image src={item.coverImage} alt={name} fill priority sizes="100vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-black/80 to-black/10" /><div className="relative flex min-h-[560px] items-end p-7 sm:p-12 lg:p-16"><div className="max-w-4xl text-white"><p className="text-sm font-bold text-white/70">{location}</p><h1 className="mt-4 text-5xl font-black leading-none tracking-tight sm:text-7xl">{name}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-white/80">{localizeField(item.intro, locale) || localizeField(item.shortDescription, locale)}</p></div></div></header>
      <div className="mx-auto mt-12 grid max-w-6xl gap-12 lg:grid-cols-[minmax(0,1fr)_320px]"><div className="space-y-10">{article.map((section: any, index: number) => <section key={section._id || index}>{section.type === "image" && section.imageUrl ? <figure><div className="relative aspect-video overflow-hidden rounded-[2rem]"><Image src={section.imageUrl} alt={localizeField(section.caption, locale) || name} fill sizes="800px" className="object-cover" /></div><figcaption className="mt-2 text-center text-sm text-ink/50">{localizeField(section.caption, locale)}</figcaption></figure> : section.type === "quote" ? <blockquote className="border-s-4 border-clay bg-sand/40 px-7 py-6 text-xl font-bold leading-9">{localizeField(section.body, locale)}</blockquote> : section.type === "list" ? <div><h2 className="text-3xl font-black">{localizeField(section.title, locale)}</h2><ul className="mt-3 list-disc space-y-2 ps-6 leading-8 text-ink/70">{(section.items || []).map((x: any, i: number) => <li key={i}>{localizeField(x, locale)}</li>)}</ul></div> : section.type === "tip" ? <div className="rounded-2xl bg-sand/60 p-6"><p className="text-xs font-black uppercase tracking-widest text-clay">{t.tip}</p><h2 className="mt-2 text-2xl font-black">{localizeField(section.title, locale)}</h2><p className="mt-2 whitespace-pre-line leading-8 text-ink/70">{localizeField(section.body, locale)}</p></div> : <div><h2 className="text-3xl font-black">{localizeField(section.title, locale)}</h2><p className="mt-2 whitespace-pre-line text-base leading-8 text-ink/70">{localizeField(section.body, locale)}</p></div>}</section>)}</div>
      <aside className="space-y-8 lg:sticky lg:top-6 lg:self-start">{item.gallery?.length ? <section><h2 className="text-xl font-black">{t.gallery}</h2><div className="mt-4"><DestinationGallery images={item.gallery} alt={name} /></div></section> : null}
        {item.recommendedAgencies?.length ? <section><h2 className="text-xl font-black">{t.agencies}</h2><div className="mt-4 space-y-4">{item.recommendedAgencies.map((entry: any, index: number) => { const agency = entry.agency || {}; const agencyName = agency.name || "Agency"; return <div key={entry._id || index} className="rounded-2xl border border-ink/10 p-4">{(agency.logo || agency.coverImage) && <div className="relative mb-3 h-24 overflow-hidden rounded-xl"><Image src={agency.logo || agency.coverImage} alt={agencyName} fill sizes="300px" className="object-cover" /></div>}<h3 className="font-black">{agencyName}</h3><p className="text-xs text-ink/50">{agency.city}</p><p className="mt-2 text-sm leading-6 text-ink/65">{localizeField(entry.description, locale) || agency.description}</p><div className="mt-4 flex flex-wrap gap-2">{entry.bookingUrl && <a href={entry.bookingUrl} target="_blank" rel="noreferrer" className="rounded-xl bg-forest px-3 py-2 text-xs font-black text-white">{t.book}</a>}{agency.whatsapp && <a href={`https://wa.me/${String(agency.whatsapp).replace(/[^0-9]/g, "")}`} target="_blank" rel="noreferrer" className="rounded-xl border px-3 py-2 text-xs font-black">WhatsApp</a>}{agency.phone && <a href={`tel:${agency.phone}`} className="rounded-xl border px-3 py-2 text-xs font-black">{t.contact}</a>}</div><div className="mt-3 flex flex-wrap gap-3 text-xs font-bold">{Object.entries(entry.socials || {}).filter(([, url]) => url).map(([key, url]) => <a key={key} href={String(url)} target="_blank" rel="noreferrer" className="text-clay">{key}</a>)}</div></div>; })}</div><p className="mt-3 text-xs leading-5 text-ink/45">Moroccan Trip does not process bookings or payments. Booking links open the agency&apos;s external website.</p></section> : null}</aside></div>
    </article></main>;
}
