// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/admin/agencies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/agencies">> = Specific
  const handler = {} as typeof import("../../app/admin/agencies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/leads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/leads">> = Specific
  const handler = {} as typeof import("../../app/admin/leads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/listings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/listings">> = Specific
  const handler = {} as typeof import("../../app/admin/listings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/messages">> = Specific
  const handler = {} as typeof import("../../app/admin/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/rental-requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/rental-requests">> = Specific
  const handler = {} as typeof import("../../app/admin/rental-requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/reports">> = Specific
  const handler = {} as typeof import("../../app/admin/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/reservations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/reservations">> = Specific
  const handler = {} as typeof import("../../app/admin/reservations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/reviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/reviews">> = Specific
  const handler = {} as typeof import("../../app/admin/reviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/travel-posts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/travel-posts">> = Specific
  const handler = {} as typeof import("../../app/admin/travel-posts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/trips/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/trips">> = Specific
  const handler = {} as typeof import("../../app/admin/trips/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/agencies/[agencyId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agencies/[agencyId]">> = Specific
  const handler = {} as typeof import("../../app/agencies/[agencyId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/agencies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agencies">> = Specific
  const handler = {} as typeof import("../../app/agencies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/agency/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agency/dashboard">> = Specific
  const handler = {} as typeof import("../../app/agency/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/agency/leads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agency/leads">> = Specific
  const handler = {} as typeof import("../../app/agency/leads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/agency/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agency/profile">> = Specific
  const handler = {} as typeof import("../../app/agency/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/agency/rental-requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agency/rental-requests">> = Specific
  const handler = {} as typeof import("../../app/agency/rental-requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/agency/reservations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agency/reservations">> = Specific
  const handler = {} as typeof import("../../app/agency/reservations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/agency/trips/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agency/trips">> = Specific
  const handler = {} as typeof import("../../app/agency/trips/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/listings/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/listings/[id]">> = Specific
  const handler = {} as typeof import("../../app/listings/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/listings/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/listings/new">> = Specific
  const handler = {} as typeof import("../../app/listings/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/messages/[conversationId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/messages/[conversationId]">> = Specific
  const handler = {} as typeof import("../../app/messages/[conversationId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/messages">> = Specific
  const handler = {} as typeof import("../../app/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/rentals/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rentals/new">> = Specific
  const handler = {} as typeof import("../../app/rentals/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/rentals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rentals">> = Specific
  const handler = {} as typeof import("../../app/rentals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/rentals/trip/[tripId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rentals/trip/[tripId]">> = Specific
  const handler = {} as typeof import("../../app/rentals/trip/[tripId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/renter/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/renter/dashboard">> = Specific
  const handler = {} as typeof import("../../app/renter/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/renter/items/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/renter/items">> = Specific
  const handler = {} as typeof import("../../app/renter/items/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/renter/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/renter/profile">> = Specific
  const handler = {} as typeof import("../../app/renter/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/travel-partners/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/travel-partners">> = Specific
  const handler = {} as typeof import("../../app/travel-partners/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/agencies/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/agencies/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/agencies/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/leads/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/leads/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/leads/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/listings/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/listings/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/listings/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/messages/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/messages/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/messages/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/reports/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reports/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/reports/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/reservations/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reservations/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/reservations/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/reviews/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reviews/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/reviews/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/travel-posts/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/travel-posts/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/travel-posts/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/trips/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/trips/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/trips/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/users/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/users/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agency/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agency/profile">> = Specific
  const handler = {} as typeof import("../../app/api/agency/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agency/renter-links/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agency/renter-links">> = Specific
  const handler = {} as typeof import("../../app/api/agency/renter-links/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agency/reservations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agency/reservations">> = Specific
  const handler = {} as typeof import("../../app/api/agency/reservations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agency/trips/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agency/trips/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/agency/trips/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agency/trips/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agency/trips">> = Specific
  const handler = {} as typeof import("../../app/api/agency/trips/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/conversations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/conversations">> = Specific
  const handler = {} as typeof import("../../app/api/conversations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/leads/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads">> = Specific
  const handler = {} as typeof import("../../app/api/leads/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/listings/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/listings/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/listings/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/listings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/listings">> = Specific
  const handler = {} as typeof import("../../app/api/listings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/messages">> = Specific
  const handler = {} as typeof import("../../app/api/messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/register">> = Specific
  const handler = {} as typeof import("../../app/api/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/rental-requests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rental-requests">> = Specific
  const handler = {} as typeof import("../../app/api/rental-requests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/rentals/unlock/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rentals/unlock">> = Specific
  const handler = {} as typeof import("../../app/api/rentals/unlock/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/renter/items/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/renter/items/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/renter/items/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/renter/items/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/renter/items">> = Specific
  const handler = {} as typeof import("../../app/api/renter/items/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/renter/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/renter/profile">> = Specific
  const handler = {} as typeof import("../../app/api/renter/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports">> = Specific
  const handler = {} as typeof import("../../app/api/reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reviews/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reviews">> = Specific
  const handler = {} as typeof import("../../app/api/reviews/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/travel-posts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/travel-posts">> = Specific
  const handler = {} as typeof import("../../app/api/travel-posts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/agency/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/agency">> = Specific
  const handler = {} as typeof import("../../app/agency/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/renter/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/renter">> = Specific
  const handler = {} as typeof import("../../app/renter/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
