import type { MetadataRoute } from "next";
import { getAgencyProfiles } from "@/lib/agency";
import { getPublishedActivities } from "@/lib/activity";
import { getPublishedAffiliateProducts } from "@/lib/affiliate-products";
import { getPlaces } from "@/lib/camping";
import { getPublishedDestinations } from "@/lib/destinations";
import { absoluteUrl } from "@/lib/seo";
const STATIC_ROUTES=[{path:"/",changeFrequency:"daily",priority:1},{path:"/marketplace",changeFrequency:"daily",priority:.95},{path:"/trips",changeFrequency:"daily",priority:.95},{path:"/agencies",changeFrequency:"daily",priority:.95},{path:"/destinations",changeFrequency:"daily",priority:.95},{path:"/rentals",changeFrequency:"daily",priority:.9},{path:"/travel-partners",changeFrequency:"weekly",priority:.8},{path:"/camping",changeFrequency:"daily",priority:.9},{path:"/activities",changeFrequency:"daily",priority:.9}] as const;
export default async function sitemap():Promise<MetadataRoute.Sitemap>{const [agencies,places,activities,products,destinations]=await Promise.all([getAgencyProfiles({limit:200}),getPlaces({limit:200}),getPublishedActivities(),getPublishedAffiliateProducts(),getPublishedDestinations()]);const staticEntries=STATIC_ROUTES.map(route=>({url:absoluteUrl(route.path),lastModified:new Date(),changeFrequency:route.changeFrequency,priority:route.priority}));const destinationEntries=(destinations as any[]).map(item=>({url:absoluteUrl(`/destinations/${item.slug}`),lastModified:item.updatedAt||item.createdAt||new Date(),changeFrequency:"weekly" as const,priority:item.featured?.85:.7}));const agencyEntries=agencies.map((agency:any)=>({url:absoluteUrl(`/agencies/${agency._id}`),lastModified:agency.updatedAt||agency.createdAt||new Date(),changeFrequency:"weekly" as const,priority:.7}));const placeEntries=places.map((place:any)=>({url:absoluteUrl(`/camping/${place.slug||place._id}`),lastModified:place.updatedAt||place.createdAt||new Date(),changeFrequency:"weekly" as const,priority:place.featured?.85:.7}));const activityEntries=activities.map((activity:any)=>({url:absoluteUrl(`/activities/${activity.slug||activity._id}`),lastModified:activity.updatedAt||activity.createdAt||new Date(),changeFrequency:"weekly" as const,priority:activity.featured?.85:.7}));const productEntries=products.map((product:any)=>({url:absoluteUrl(`/marketplace/${product.slug||product._id}`),lastModified:product.updatedAt||product.createdAt||new Date(),changeFrequency:"weekly" as const,priority:product.featured?.9:.75}));return [...staticEntries,...destinationEntries,...agencyEntries,...placeEntries,...activityEntries,...productEntries];}
