import Image from "next/image";
import Link from "next/link";
import { MapPin, Sparkles } from "lucide-react";
import { AffiliatePriceDisplay } from "@/components/affiliate-price-display";
import { ActivityBookLink } from "@/components/activity-analytics";
import { ActivityTypeBadge } from "@/components/activity-type-badge";
import { type SiteLocale, withLocale } from "@/lib/i18n";

export function ActivityCard({ activity, locale }: { activity: any; locale: SiteLocale }) {
  const href = withLocale(`/activities/${activity.slug || activity._id}`, locale);
  return <article className="group flex h-full flex-col overflow-hidden rounded-[2.25rem] border border-white/80 bg-white shadow-[0_24px_65px_rgba(15,61,46,.11)] transition duration-300 hover:-translate-y-1.5 hover:shadow-[0_34px_90px_rgba(15,61,46,.18)]"><Link href={href} className="relative block h-80 overflow-hidden bg-emerald-950 sm:h-[22rem]"><Image src={activity.image} alt={activity.title} fill sizes="(max-width: 768px) 100vw, (max-width: 1280px) 50vw, 33vw" className="object-cover transition duration-700 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-emerald-950/80 via-transparent to-black/10" />{activity.featured ? <span className="absolute left-4 top-4 inline-flex items-center gap-2 rounded-full bg-clay px-4 py-2 text-xs font-black uppercase tracking-wide text-white shadow-lg"><Sparkles className="h-3.5 w-3.5" />Featured</span> : null}<div className="absolute bottom-5 left-5 right-5 text-white"><p className="flex items-center gap-2 text-xs font-black uppercase tracking-[.18em] text-white/80"><MapPin className="h-4 w-4" />{activity.location}</p><h2 className="mt-2 text-2xl font-black leading-tight sm:text-3xl">{activity.title}</h2></div></Link><div className="flex flex-1 flex-col p-6 sm:p-7"><p className="text-xs font-black uppercase tracking-[.2em] text-clay">{activity.category}</p><p className="mt-3 line-clamp-3 flex-1 text-sm leading-7 text-ink/60">{activity.shortDescription}</p><div className="mt-4 flex flex-wrap gap-2">{activity.types.slice(0, 3).map((item: string) => <ActivityTypeBadge key={item} type={item} compact />)}</div><div className="mt-6 border-t border-ink/5 pt-5"><AffiliatePriceDisplay price={activity.price} currency={activity.currency} discountedPrice={activity.discountedPrice} /></div><div className="mt-5 grid grid-cols-[.8fr_1.2fr] gap-3"><Link href={href} className="inline-flex justify-center rounded-full border border-forest px-4 py-3.5 text-sm font-black text-forest transition hover:bg-emerald-50">Details</Link><ActivityBookLink activityId={activity._id} href={activity.affiliateUrl} className="inline-flex justify-center rounded-full bg-forest px-4 py-3.5 text-sm font-black text-white shadow-[0_14px_30px_rgba(15,61,46,.2)] transition hover:bg-clay">{locale === "ar" ? "احجز الآن" : "Book Now"}</ActivityBookLink></div></div></article>;
}
