import Image from "next/image";
import Link from "next/link";
import { MapPin } from "lucide-react";
import { AffiliatePriceDisplay } from "@/components/affiliate-price-display";
import { CampingBadge } from "@/components/camping-badges";
import { VisitNowLink } from "@/components/camping-analytics";
import { SiteLocale, withLocale } from "@/lib/i18n";

export function CampingCard({ place, locale, compact = false }: { place: any; locale: SiteLocale; compact?: boolean }) {
  const href = withLocale(`/camping/${place.slug || place._id}`, locale);
  return <article className="group flex h-full flex-col overflow-hidden rounded-[2.25rem] border border-white/80 bg-white shadow-[0_24px_65px_rgba(15,61,46,.11)] transition duration-300 hover:-translate-y-1.5 hover:shadow-[0_34px_90px_rgba(15,61,46,.18)]"><Link href={href} className={`relative block overflow-hidden bg-emerald-950 ${compact ? "h-64" : "h-80 sm:h-[22rem]"}`}><Image src={place.image} alt={place.name} fill sizes="(max-width: 768px) 100vw, (max-width: 1280px) 50vw, 33vw" className="object-cover transition duration-700 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-emerald-950/75 via-transparent to-black/10" />{place.featured ? <span className="absolute left-4 top-4 rounded-full bg-clay px-4 py-2 text-xs font-black uppercase tracking-wide text-white shadow-lg">Featured</span> : null}<div className="absolute bottom-5 left-5 right-5 text-white"><p className="flex items-center gap-2 text-xs font-black uppercase tracking-[.18em] text-white/80"><MapPin className="h-4 w-4" />{place.location}</p><h2 className="mt-2 text-2xl font-black leading-tight sm:text-3xl">{place.name}</h2></div></Link><div className="flex flex-1 flex-col p-6 sm:p-7"><p className="text-xs font-black uppercase tracking-[.2em] text-clay">{place.category}</p><p className="mt-3 line-clamp-3 flex-1 text-sm leading-7 text-ink/60">{place.shortDescription || place.description}</p><div className="mt-4 flex flex-wrap gap-2">{[...(place.types || []), ...(place.features || [])].slice(0, 3).map((x: string) => <CampingBadge key={x} label={x} />)}</div><div className="mt-6 flex items-end justify-between gap-4 border-t border-ink/5 pt-5"><AffiliatePriceDisplay price={place.price} currency={place.currency} discountedPrice={place.discountedPrice} /><span className="text-xs font-bold text-ink/40">Partner listing</span></div><div className="mt-5 grid grid-cols-[.8fr_1.2fr] gap-3"><Link href={href} className="rounded-full border border-forest px-4 py-3.5 text-center text-sm font-black text-forest transition hover:bg-emerald-50">Details</Link><VisitNowLink id={place._id} href={place.affiliateUrl} className="rounded-full bg-forest px-4 py-3.5 text-center text-sm font-black text-white shadow-[0_14px_30px_rgba(15,61,46,.2)] transition hover:bg-clay">Visit Now</VisitNowLink></div></div></article>;
}
