"use client";

import Image from "next/image";
import { useState } from "react";
import { uploadImage } from "@/lib/image-upload";
import { ACCEPTED_IMAGE_INPUT, validateImageFiles } from "@/lib/image-upload-shared";

type Localized = { ar: string; fr: string; en: string };
type Props = { destination?: any };
const empty: Localized = { ar: "", fr: "", en: "" };
const clone = (value: any) => JSON.parse(JSON.stringify(value));
const cities = ["Casablanca", "Marrakech", "Rabat", "Agadir", "Tangier", "Fes", "Chefchaouen", "Ouarzazate", "Essaouira", "Merzouga", "Ifrane", "Tetouan", "Dakhla", "Other"];
const regions = ["Casablanca-Settat", "Marrakech-Safi", "Rabat-Salé-Kénitra", "Souss-Massa", "Tanger-Tétouan-Al Hoceïma", "Fès-Meknès", "Drâa-Tafilalet", "Oriental", "Béni Mellal-Khénifra", "Dakhla-Oued Ed-Dahab", "Laâyoune-Sakia El Hamra", "Guelmim-Oued Noun", "Other"];
const articleTypes = ["heading", "paragraph", "list", "quote", "image", "tip"] as const;

function Section({ title, description, children, defaultOpen = true }: { title: string; description?: string; children: React.ReactNode; defaultOpen?: boolean }) {
  return <details open={defaultOpen} className="overflow-hidden rounded-2xl border border-ink/10"><summary className="cursor-pointer list-none bg-sand/40 px-5 py-4"><span className="text-lg font-black">{title}</span>{description ? <span className="mt-1 block text-xs text-ink/50">{description}</span> : null}</summary><div className="space-y-5 p-5">{children}</div></details>;
}

function AgencyEditor({ agency, index, onChange, onRemove, onMove, busy, onNotice }: { agency: any; index: number; onChange: (value: any) => void; onRemove: () => void; onMove: (direction: -1 | 1) => void; busy: boolean; onNotice: (value: string) => void }) {
  async function uploadLogo(file: File) {
    const error = validateImageFiles({ files: [file], maxFiles: 1, label: "Agency logo" });
    if (error) return onNotice(error);
    try { const url = await uploadImage(file); onChange({ ...agency, logo: url }); onNotice("Agency logo uploaded."); } catch (error) { onNotice(error instanceof Error ? error.message : "Logo upload failed."); }
  }
  const field = (key: string, label: string, placeholder: string, required = false) => <label className="block text-xs font-black text-ink/60">{label}{required ? <span className="ms-1 text-clay">*</span> : null}<input value={agency?.[key] || ""} onChange={(e) => onChange({ ...agency, [key]: e.target.value })} placeholder={placeholder} className="mt-1.5 w-full rounded-xl border border-ink/10 px-3 py-2.5 text-sm font-medium" /></label>;
  return <div className="rounded-2xl border border-ink/10 bg-white p-4 shadow-sm">
    <div className="flex items-center justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-clay">Agency #{index + 1}</p><p className="mt-1 text-sm font-black">{agency?.name || "New agency"}</p></div><div className="flex items-center gap-1"><button type="button" onClick={() => onMove(-1)} disabled={index === 0} className="rounded-lg border px-2 py-1 text-xs disabled:opacity-30" aria-label="Move agency up">↑</button><button type="button" onClick={() => onMove(1)} disabled={index === 0 && false} className="rounded-lg border px-2 py-1 text-xs disabled:opacity-30" aria-label="Move agency down">↓</button><button type="button" onClick={onRemove} className="rounded-lg border border-red-200 px-2.5 py-1 text-xs font-bold text-red-700">Remove</button></div></div>
    <div className="mt-4 grid gap-3 md:grid-cols-2">
      {field("name", "Agency name", "Atlas Travel", true)}
      {field("instagram", "Instagram", "https://instagram.com/agencyname")}
      {field("whatsapp", "WhatsApp", "+212 6... or https://wa.me/212...")}
      {field("bookNowUrl", "Book Now URL", "https://agencywebsite.com/book", true)}
    </div>
    <div className="mt-4 grid gap-4 md:grid-cols-[auto_1fr] md:items-center">
      <div>{agency?.logo ? <Image src={agency.logo} alt={`${agency.name || "Agency"} logo`} width={72} height={72} className="h-[72px] w-[72px] rounded-2xl border border-ink/10 object-cover" /> : <div className="flex h-[72px] w-[72px] items-center justify-center rounded-2xl bg-sand text-xs font-black text-forest">Logo</div>}</div>
      <label className="block text-xs font-black text-ink/60">Agency logo<input type="file" accept={ACCEPTED_IMAGE_INPUT} disabled={busy} onChange={(e) => { const file = e.target.files?.[0]; if (file) void uploadLogo(file); }} className="mt-1.5 block w-full text-sm" /></label>
    </div>
  </div>;
}

export function DestinationManager({ destination }: Props) {
  const [form, setForm] = useState<any>(destination || { name: { ...empty }, slug: "", location: { ...empty }, category: { ...empty }, shortDescription: { ...empty }, intro: { ...empty }, coverImage: "", gallery: [], article: [], destinationAgencies: [], seoTitle: { ...empty }, seoDescription: { ...empty }, featured: false, published: false, displayOrder: 0 });
  const [busy, setBusy] = useState(false);
  const [notice, setNotice] = useState("");
  const [lang, setLang] = useState<keyof Localized>("fr");
  const set = (key: string, value: any) => setForm((current: any) => ({ ...current, [key]: value }));
  const updateArrayItem = (key: string, index: number, value: any) => { const next = clone(form[key] || []); next[index] = value; set(key, next); };
  const move = (key: string, index: number, direction: -1 | 1) => { const next = clone(form[key] || []); const target = index + direction; if (target < 0 || target >= next.length) return; [next[index], next[target]] = [next[target], next[index]]; set(key, next); };
  async function uploadSingle(file: File, onSuccess: (url: string) => void, label: string) { const error = validateImageFiles({ files: [file], maxFiles: 1, label }); if (error) return setNotice(error); setBusy(true); try { onSuccess(await uploadImage(file)); setNotice(`${label} uploaded.`); } catch (error) { setNotice(error instanceof Error ? error.message : "Upload failed."); } finally { setBusy(false); } }
  async function uploadGallery(files: FileList | null) { const list = Array.from(files || []); if (!list.length) return; const error = validateImageFiles({ files: list, maxFiles: 20, label: "gallery images" }); if (error) return setNotice(error); setBusy(true); try { const urls = await Promise.all(list.map(uploadImage)); set("gallery", [...(form.gallery || []), ...urls.map((url) => ({ url, publicId: "", caption: { ...empty } }))]); setNotice("Gallery uploaded."); } catch (error) { setNotice(error instanceof Error ? error.message : "Upload failed."); } finally { setBusy(false); } }
  function addAgency() { set("destinationAgencies", [...(form.destinationAgencies || []), { name: "", logo: "", instagram: "", whatsapp: "", bookNowUrl: "" }]); }
  function addArticle(type = "paragraph") { set("article", [...(form.article || []), { type, title: { ...empty }, body: { ...empty }, imageUrl: "", imagePublicId: "", caption: { ...empty }, items: [] }]); }
  function makeSlug() { const source = form.name?.en || form.name?.fr || form.name?.ar || ""; set("slug", String(source).normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")); }
  async function save() { setBusy(true); setNotice(""); try { const payload = clone(form); if (!payload.slug) { const source = payload.name?.en || payload.name?.fr || payload.name?.ar || ""; payload.slug = String(source).normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""); } if (!payload.slug) throw new Error("Please enter a destination name before saving."); const response = await fetch(destination ? `/api/admin/destinations/${destination._id}` : "/api/admin/destinations", { method: destination ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Could not save destination."); setForm(data.destination); setNotice("Destination saved successfully."); } catch (error) { setNotice(error instanceof Error ? error.message : "Save failed."); } finally { setBusy(false); } }
  const localized = (key: string) => form[key]?.[lang] || "";
  const setLocalized = (key: string, value: string) => set(key, { ...(form[key] || empty), [lang]: value });
  const agencyList = form.destinationAgencies || [];

  return <section className="space-y-5 rounded-[2rem] bg-white p-4 shadow-card sm:p-7">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.2em] text-clay">Destination editor</p><h2 className="mt-1 text-3xl font-black">{destination ? "Edit destination" : "Create destination"}</h2><p className="mt-1 text-sm text-ink/55">Manage destination content and direct-to-agency booking links from one form.</p></div><div className="flex gap-2 rounded-xl bg-sand p-1">{(["ar", "fr", "en"] as const).map((value) => <button key={value} type="button" onClick={() => setLang(value)} className={`rounded-lg px-3 py-2 text-xs font-black ${lang === value ? "bg-white" : "text-ink/50"}`}>{value === "ar" ? "🇲🇦 العربية" : value === "fr" ? "🇫🇷 Français" : "🇬🇧 English"}</button>)}</div></div>
    {notice ? <div className="rounded-xl bg-sand p-3 text-sm font-bold">{notice}</div> : null}

    <Section title="1. Destination" description="The essential information visitors need."><div className="space-y-5"><label className="block text-sm font-bold">Destination name <span className="text-clay">*</span><input dir={lang === "ar" ? "rtl" : "ltr"} value={localized("name")} onChange={(e) => setLocalized("name", e.target.value)} placeholder="e.g. Chefchaouen" className="mt-2 w-full rounded-xl border border-ink/10 px-4 py-3" /></label><div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-bold">City<select value={form.city || form.location?.fr || ""} onChange={(e) => { set("city", e.target.value); set("location", { ...(form.location || empty), [lang]: e.target.value }); }} className="mt-2 w-full rounded-xl border border-ink/10 px-4 py-3"><option value="">Select city</option>{cities.map((city) => <option key={city}>{city}</option>)}</select></label><label className="text-sm font-bold">Region<select value={form.region || ""} onChange={(e) => set("region", e.target.value)} className="mt-2 w-full rounded-xl border border-ink/10 px-4 py-3"><option value="">Select region</option>{regions.map((region) => <option key={region}>{region}</option>)}</select></label></div><label className="block text-sm font-bold">Short description <span className="text-clay">*</span><textarea dir={lang === "ar" ? "rtl" : "ltr"} value={localized("shortDescription")} onChange={(e) => setLocalized("shortDescription", e.target.value)} rows={3} placeholder="A short introduction visitors can understand quickly." className="mt-2 w-full rounded-xl border border-ink/10 p-3" /></label><label className="block text-sm font-bold">Slug <span className="text-ink/40">(automatic)</span><div className="mt-2 flex gap-2"><input value={form.slug || ""} onChange={(e) => set("slug", e.target.value)} className="w-full rounded-xl border border-ink/10 px-4 py-3" /><button type="button" onClick={makeSlug} className="rounded-xl border px-4 text-xs font-black">Generate</button></div></label><div><p className="text-sm font-bold">Cover image <span className="text-clay">*</span></p>{form.coverImage ? <Image src={form.coverImage} alt="Destination cover" width={1200} height={500} className="mt-2 h-52 w-full rounded-2xl object-cover" /> : <div className="mt-2 rounded-2xl border border-dashed p-8 text-center text-sm text-ink/45">Upload a strong cover photo</div>}<input type="file" accept={ACCEPTED_IMAGE_INPUT} disabled={busy} onChange={(e) => { const file = e.target.files?.[0]; if (file) void uploadSingle(file, (url) => set("coverImage", url), "Cover image"); }} className="mt-3 block w-full text-sm" /></div></div></Section>

    <Section title="2. Photos" description="Upload a gallery and arrange it in the order visitors should see it."><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-ink/55">Up to 20 images per upload. Captions are optional.</p><input type="file" multiple accept={ACCEPTED_IMAGE_INPUT} disabled={busy} onChange={(e) => void uploadGallery(e.target.files)} /></div><div className="space-y-3">{(form.gallery || []).map((item: any, index: number) => <div key={item._id || index} className="grid gap-3 rounded-2xl border p-3 md:grid-cols-[120px_1fr_auto] md:items-center"><Image src={item.url} alt="Gallery" width={120} height={120} className="aspect-square rounded-xl object-cover" /><input dir={lang === "ar" ? "rtl" : "ltr"} value={item.caption?.[lang] || ""} onChange={(e) => updateArrayItem("gallery", index, { ...item, caption: { ...(item.caption || empty), [lang]: e.target.value } })} placeholder="Optional caption" className="rounded-xl border border-ink/10 px-3 py-2" /><div className="flex gap-2"><button type="button" onClick={() => move("gallery", index, -1)} aria-label="Move gallery image up">↑</button><button type="button" onClick={() => move("gallery", index, 1)} aria-label="Move gallery image down">↓</button><button type="button" onClick={() => set("gallery", form.gallery.filter((_: any, itemIndex: number) => itemIndex !== index))} className="text-red-700" aria-label="Remove gallery image">×</button></div></div>)}</div></Section>

    <Section title="3. Agencies" description="Independent destination-specific listings. No agency account, profile, user ID, or dashboard is involved."><div className="rounded-xl bg-sand/50 p-3 text-sm text-ink/60">Add the public agency information once. Book Now always opens the exact external URL entered here.</div><div className="flex items-center justify-between gap-3"><div><p className="text-sm font-black">{agencyList.length} {agencyList.length === 1 ? "agency" : "agencies"}</p><p className="text-xs text-ink/45">Each destination can have many agencies, with its own booking URL.</p></div><button type="button" onClick={addAgency} className="rounded-xl bg-forest px-4 py-2 text-sm font-black text-white">+ Add agency</button></div><div className="space-y-3">{agencyList.map((agency: any, index: number) => <AgencyEditor key={agency._id || index} agency={agency} index={index} busy={busy} onNotice={setNotice} onChange={(value) => updateArrayItem("destinationAgencies", index, value)} onRemove={() => set("destinationAgencies", agencyList.filter((_: any, itemIndex: number) => itemIndex !== index))} onMove={(direction) => move("destinationAgencies", index, direction)} />)}</div></Section>

    <Section title="4. Destination article" description="Keep the existing destination article system intact."><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-ink/55">Write useful travel information without HTML.</p><button type="button" onClick={() => addArticle()} className="rounded-xl bg-forest px-4 py-2 text-sm font-black text-white">+ Add section</button></div>{(form.article || []).map((section: any, index: number) => <div key={section._id || index} className="space-y-4 rounded-2xl border border-ink/10 p-4"><div className="flex flex-wrap items-center gap-2"><select value={section.type} onChange={(e) => updateArrayItem("article", index, { ...section, type: e.target.value })} className="rounded-lg border px-3 py-2 text-sm">{articleTypes.map((type) => <option key={type}>{type}</option>)}</select><button type="button" onClick={() => move("article", index, -1)}>↑</button><button type="button" onClick={() => move("article", index, 1)}>↓</button><button type="button" onClick={() => set("article", form.article.filter((_: any, itemIndex: number) => itemIndex !== index))} className="ms-auto text-red-700">Delete</button></div><input dir={lang === "ar" ? "rtl" : "ltr"} value={section.title?.[lang] || ""} onChange={(e) => updateArrayItem("article", index, { ...section, title: { ...(section.title || empty), [lang]: e.target.value } })} placeholder="Section title" className="w-full rounded-xl border px-3 py-2" />{section.type !== "image" && <textarea dir={lang === "ar" ? "rtl" : "ltr"} rows={5} value={section.body?.[lang] || ""} onChange={(e) => updateArrayItem("article", index, { ...section, body: { ...(section.body || empty), [lang]: e.target.value } })} placeholder="Write the section here..." className="w-full rounded-xl border px-3 py-3" />}{section.type === "image" ? <div><input type="file" accept={ACCEPTED_IMAGE_INPUT} disabled={busy} onChange={(e) => { const file = e.target.files?.[0]; if (file) void uploadSingle(file, (url) => updateArrayItem("article", index, { ...section, imageUrl: url }), "Article image"); }} className="block w-full text-sm" />{section.imageUrl ? <Image src={section.imageUrl} alt="Article" width={800} height={450} className="mt-3 h-48 w-full rounded-xl object-cover" /> : null}</div> : null}{section.type === "list" ? <textarea rows={4} value={(section.items || []).map((item: any) => item?.[lang] || "").join("\n")} onChange={(e) => updateArrayItem("article", index, { ...section, items: e.target.value.split("\n").map((value) => ({ ...empty, [lang]: value })) })} placeholder="One list item per line" className="w-full rounded-xl border px-3 py-3" /> : null}</div>)}</Section>

    <Section title="5. SEO & publishing" description="Keep destination search visibility and publishing controls intact."><div className="space-y-4"><label className="block text-sm font-bold">Intro<textarea dir={lang === "ar" ? "rtl" : "ltr"} rows={4} value={localized("intro")} onChange={(e) => setLocalized("intro", e.target.value)} className="mt-2 w-full rounded-xl border p-3" /></label><div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-bold">SEO title<input dir={lang === "ar" ? "rtl" : "ltr"} value={localized("seoTitle")} onChange={(e) => setLocalized("seoTitle", e.target.value)} className="mt-2 w-full rounded-xl border px-3 py-2" /></label><label className="text-sm font-bold">SEO description<textarea dir={lang === "ar" ? "rtl" : "ltr"} rows={2} value={localized("seoDescription")} onChange={(e) => setLocalized("seoDescription", e.target.value)} className="mt-2 w-full rounded-xl border p-3" /></label></div><div className="flex flex-wrap gap-6"><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={Boolean(form.featured)} onChange={(e) => set("featured", e.target.checked)} /> Featured</label><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={Boolean(form.published)} onChange={(e) => set("published", e.target.checked)} /> Published</label><label className="flex items-center gap-2 text-sm font-bold">Order<input type="number" value={form.displayOrder ?? 0} onChange={(e) => set("displayOrder", Number(e.target.value))} className="w-24 rounded-lg border px-2 py-1" /></label></div></div></Section>

    <div className="sticky bottom-4 z-10 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-ink/10 bg-white/95 p-3 shadow-lg backdrop-blur"><p className="text-xs font-bold text-ink/50">Moroccan Trip is a discovery/referral platform. Bookings happen directly on the agency website.</p><button type="button" onClick={() => void save()} disabled={busy} className="rounded-xl bg-forest px-6 py-3 text-sm font-black text-white disabled:opacity-50">{busy ? "Saving…" : "Save destination"}</button></div>
  </section>;
}
