import Image from "next/image";
import Link from "next/link";
import { PackageCheck, ShieldCheck } from "lucide-react";
import { ProductBuyLink } from "@/components/product-analytics";
import { ProductBadge, ProductFeature } from "@/components/product-badges";
import { AffiliatePriceDisplay } from "@/components/affiliate-price-display";
import { type SiteLocale, withLocale } from "@/lib/i18n";

export function ProductCard({ product, locale, compact = false }: { product: any; locale: SiteLocale; compact?: boolean }) {
  const href = withLocale(`/marketplace/${product.slug || product._id}`, locale);
  const badges = Array.from(new Set([...(product.featured ? ["Featured"] : []), ...(product.badges || [])])).slice(0, 3) as string[];
  return <article className="group flex h-full flex-col overflow-hidden rounded-[2.25rem] border border-white/80 bg-white shadow-[0_24px_65px_rgba(15,61,46,.11)] transition duration-300 hover:-translate-y-1.5 hover:shadow-[0_34px_90px_rgba(15,61,46,.18)]"><Link href={href} className={`relative block overflow-hidden bg-[linear-gradient(145deg,#f8faf9,#edf4f0)] ${compact ? "h-64" : "h-80 sm:h-[22rem]"}`}><Image src={product.image} alt={product.title} fill sizes="(max-width: 768px) 100vw, (max-width: 1280px) 50vw, 33vw" className="object-contain p-5 transition duration-700 group-hover:scale-105 sm:p-7" /><div className="absolute inset-x-4 top-4 flex flex-wrap gap-2">{badges.map((badge) => <ProductBadge key={badge} label={badge} />)}</div><span className="absolute bottom-4 right-4 inline-flex items-center gap-1.5 rounded-full bg-white/90 px-3 py-2 text-xs font-black text-forest shadow-lg backdrop-blur"><ShieldCheck className="h-4 w-4" />Partner product</span></Link><div className="flex flex-1 flex-col p-6 sm:p-7"><div className="flex items-center justify-between gap-3 text-xs font-black uppercase tracking-[.18em] text-clay"><span>{product.category || product.productType || "Marketplace"}</span>{product.brand ? <span className="text-ink/45">{product.brand}</span> : null}</div><Link href={href}><h2 className="mt-3 text-2xl font-black leading-tight text-ink transition group-hover:text-clay sm:text-[1.7rem]">{product.title}</h2></Link><p className="mt-3 line-clamp-3 flex-1 text-sm leading-7 text-ink/60">{product.shortDescription || product.description}</p>{product.quickInfo?.length ? <div className="mt-4 grid grid-cols-2 gap-2">{product.quickInfo.slice(0, 2).map((item: any) => <div key={`${item.label}-${item.value}`} className="flex items-center gap-2 rounded-[1rem] bg-sand/45 p-3 text-xs text-ink/65"><PackageCheck className="h-4 w-4 shrink-0 text-forest" /><span><strong className="block text-ink">{item.value}</strong>{item.label}</span></div>)}</div> : null}{product.features?.length ? <div className="mt-4 flex flex-wrap gap-2">{product.features.slice(0, 2).map((feature: string) => <ProductFeature key={feature} label={feature} compact />)}</div> : null}<div className="mt-6 border-t border-ink/5 pt-5"><AffiliatePriceDisplay price={product.price} currency={product.currency} discountedPrice={product.discountedPrice} /></div><div className="mt-5 grid grid-cols-[.8fr_1.2fr] gap-3"><Link href={href} className="inline-flex items-center justify-center rounded-full border border-forest px-4 py-3.5 text-sm font-black text-forest transition hover:bg-emerald-50">Details</Link><ProductBuyLink productId={product._id} href={product.affiliateUrl} className="inline-flex items-center justify-center rounded-full bg-forest px-4 py-3.5 text-sm font-black text-white shadow-[0_14px_30px_rgba(15,61,46,.2)] transition hover:bg-clay">{locale === "ar" ? "اشتر الآن" : "Buy Now"}</ProductBuyLink></div></div></article>;
}
