import type { Metadata } from "next";
import Image from "next/image";
import { PackageSearch, Search, ShieldCheck, SlidersHorizontal } from "lucide-react";
import { ProductCard } from "@/components/product-card";
import { getAffiliateProductFilterOptions, getPublishedAffiliateProducts } from "@/lib/affiliate-products";
import { getDirection, resolveLocale } from "@/lib/i18n";
import { buildPageMetadata } from "@/lib/seo";
export const revalidate = 60;
export const metadata: Metadata = buildPageMetadata({ title: "Premium Affiliate Marketplace | Moroccan Trip", description: "Discover trusted, hand-picked travel and outdoor products from affiliate partners.", path: "/marketplace", image: "/images/buy-gear.jpg" });
export default async function MarketplacePage({ searchParams }: { searchParams: Promise<{ lang?: string; q?: string; category?: string; brand?: string; location?: string; tag?: string; badge?: string; feature?: string; sort?: string }> }) {
  const params = await searchParams; const locale = resolveLocale(params.lang); const isArabic = locale === "ar"; const filters = { q: params.q || "", category: params.category || "", brand: params.brand || "", location: params.location || "", tag: params.tag || "", badge: params.badge || "", feature: params.feature || "", sort: params.sort || "newest" };
  const [products, options, featured] = await Promise.all([getPublishedAffiliateProducts(filters), getAffiliateProductFilterOptions(), getPublishedAffiliateProducts({ featured: true, limit: 4 })]);
  const select = (name: keyof typeof filters, label: string, values: string[]) => <select name={name} defaultValue={filters[name]} className="min-w-0 rounded-[1.15rem] border border-ink/10 bg-sand/30 px-4 py-3.5 text-sm font-semibold outline-none focus:border-clay focus:bg-white"><option value="">{label}</option>{values.map((value) => <option key={value}>{value}</option>)}</select>;
  return <main dir={getDirection(locale)} className="page-shell max-w-[1440px] space-y-14 pb-24 sm:space-y-20"><section className="relative min-h-[640px] overflow-hidden rounded-[2.5rem] bg-emerald-950 shadow-[0_35px_100px_rgba(15,61,46,.3)] sm:rounded-[3rem]"><Image src="/images/buy-gear.jpg" alt="Camping equipment and outdoor gear" fill priority sizes="100vw" className="object-cover object-[center_52%]" /><div className="absolute inset-0 bg-[linear-gradient(112deg,rgba(2,18,13,.98),rgba(15,61,46,.84)_58%,rgba(249,115,22,.38))]" /><div className="relative flex min-h-[640px] items-end px-6 py-10 sm:px-10 sm:py-14 lg:px-16 lg:py-16"><div className="max-w-4xl text-white"><p className="inline-flex rounded-full border border-white/15 bg-white/10 px-4 py-2 text-xs font-black uppercase tracking-[.28em] backdrop-blur">Premium Affiliate Marketplace</p><h1 className="mt-6 text-4xl font-black leading-[1.03] tracking-[-.04em] sm:text-6xl lg:text-7xl">{isArabic ? "منتجات مختارة بثقة لمغامرتك القادمة" : "Trusted gear for better adventures"}</h1><p className="mt-6 max-w-3xl text-base leading-8 text-white/78 sm:text-lg">Curated products, transparent trust indicators, and direct access to trusted partner stores.</p><div className="mt-8 flex flex-wrap gap-3 text-xs font-bold text-white/85"><span className="inline-flex items-center gap-2 rounded-full bg-white/10 px-4 py-2 backdrop-blur"><ShieldCheck className="h-4 w-4" />Trusted suppliers</span><span className="rounded-full bg-white/10 px-4 py-2 backdrop-blur">Outdoor-ready gear</span><span className="rounded-full bg-white/10 px-4 py-2 backdrop-blur">Direct partner access</span></div></div></div></section>
  {featured.length ? <section className="rounded-[2.75rem] bg-[linear-gradient(145deg,#fff5e8,#ffffff_55%,#edf7f2)] p-5 shadow-[0_30px_90px_rgba(15,61,46,.11)] sm:p-9 lg:p-12"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-black uppercase tracking-[.25em] text-clay">Editors selection</p><h2 className="mt-3 text-3xl font-black tracking-[-.03em] text-ink sm:text-5xl">Featured Products</h2></div><p className="max-w-lg text-sm leading-7 text-ink/55">Standout gear selected for quality, usefulness, and outdoor confidence.</p></div><div className="mt-9 grid gap-7 md:grid-cols-2 xl:grid-cols-3">{featured.map((product) => <ProductCard key={product._id} product={product} locale={locale} />)}</div></section> : null}
  <section className="rounded-[2rem] border border-white/80 bg-white/95 p-4 shadow-[0_20px_60px_rgba(15,61,46,.13)] backdrop-blur-xl sm:p-5"><div className="mb-4 flex items-center gap-3"><span className="rounded-full bg-orange-50 p-2.5 text-clay"><SlidersHorizontal className="h-5 w-5" /></span><div><h2 className="font-black text-ink">Refine the catalog</h2><p className="text-xs text-ink/45">{products.length} products available</p></div></div><form className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><input type="hidden" name="lang" value={locale} /><label className="relative sm:col-span-2"><Search className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-ink/40" /><input name="q" defaultValue={filters.q} placeholder="Search by product title" className="w-full rounded-[1.15rem] border border-ink/10 bg-sand/30 py-3.5 pl-11 pr-4 text-sm outline-none focus:border-clay focus:bg-white" /></label>{select("category", "All categories", options.categories)}{select("brand", "All brands", options.brands)}{select("location", "All locations", options.locations)}{select("tag", "All tags", options.tags)}{select("badge", "All badges", options.badges)}{select("feature", "All features", options.features)}<select name="sort" defaultValue={filters.sort} className="rounded-[1.15rem] border border-ink/10 bg-sand/30 px-4 py-3.5 text-sm font-semibold"><option value="newest">Newest first</option><option value="popular">Most popular</option><option value="featured">Featured first</option></select><button className="rounded-[1.15rem] bg-forest px-6 py-3.5 text-sm font-black text-white shadow-[0_12px_28px_rgba(15,61,46,.2)] transition hover:bg-clay">Apply filters</button></form></section>
  <section className="space-y-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-black uppercase tracking-[.25em] text-clay">Curated outdoor catalog</p><h2 className="mt-3 text-3xl font-black tracking-[-.03em] text-ink sm:text-5xl">Explore Products</h2></div><p className="rounded-full bg-emerald-50 px-4 py-2 text-sm font-black text-forest">{products.length} products</p></div>{products.length ? <div className="grid gap-8 md:grid-cols-2 xl:grid-cols-3">{products.map((product) => <ProductCard key={product._id} product={product} locale={locale} />)}</div> : <div className="rounded-[2.5rem] border border-dashed border-ink/15 bg-white p-12 text-center shadow-card"><PackageSearch className="mx-auto h-16 w-16 text-clay/60" /><h2 className="mt-5 text-2xl font-black text-ink">No products match these filters</h2><p className="mt-3 text-sm text-ink/55">Try removing a filter or explore another category.</p></div>}</section></main>;
}
