import { AFFILIATE_CURRENCIES, parseAffiliatePrice } from "@/lib/affiliate-price";
import { ACTIVITY_TYPES, type ActivityType } from "@/lib/activity-types";
import { connectToDatabase } from "@/lib/db";
import { serializeDocument } from "@/lib/utils";
import Activity from "@/models/Activity";

export type ActivityInput = { slug: string; image: string; galleryImages: string[]; ogImage: string; title: string; metaTitle: string; metaDescription: string; shortDescription: string; description: string; category: string; location: string; affiliateUrl: string; price: number; currency: string; discountedPrice: number | null; types: ActivityType[]; featured: boolean; status: "draft" | "published" };
const clean = (value: unknown) => typeof value === "string" ? value.trim() : "";
export function slugifyActivity(value: string) { return value.toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 100); }
function escapeRegex(value: string) { return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"); }
async function ensurePublishedActivitySlugs() { const missing = await Activity.find({ status: "published", $or: [{ slug: { $exists: false } }, { slug: "" }] }).select("_id title").lean(); await Promise.all(missing.map((activity: any) => { const base = slugifyActivity(activity.title) || "activity"; return Activity.updateOne({ _id: activity._id }, { $set: { slug: `${base}-${String(activity._id).slice(-6)}` } }); })); }
function isHttpUrl(value: string) { try { const url = new URL(value); return url.protocol === "https:" || url.protocol === "http:"; } catch { return false; } }
export function validateActivityPayload(payload: unknown): { data: ActivityInput } | { error: string } {
  const input = (payload || {}) as Record<string, unknown>; const image = clean(input.image); const galleryImages = Array.isArray(input.galleryImages) ? Array.from(new Set(input.galleryImages.map(clean).filter(Boolean))).slice(0, 12) : []; const ogImage = clean(input.ogImage); const title = clean(input.title); const slug = slugifyActivity(clean(input.slug) || title); const metaTitle = clean(input.metaTitle); const metaDescription = clean(input.metaDescription); const shortDescription = clean(input.shortDescription); const description = clean(input.description); const category = clean(input.category); const location = clean(input.location); const affiliateUrl = clean(input.affiliateUrl); const price = parseAffiliatePrice(input.price); const currency = clean(input.currency) || "MAD"; const discountedPrice = parseAffiliatePrice(input.discountedPrice); const featured = input.featured === true; const status = input.status === "published" ? "published" : "draft"; const types = Array.isArray(input.types) ? Array.from(new Set(input.types.filter((type): type is ActivityType => typeof type === "string" && (ACTIVITY_TYPES as readonly string[]).includes(type)))) : [];
  if (!slug) return { error: "Enter a valid activity slug." }; if (!isHttpUrl(image) || galleryImages.some((item) => !isHttpUrl(item))) return { error: "Upload valid Cloudinary activity images." }; if (ogImage && !isHttpUrl(ogImage)) return { error: "Open Graph image must be a valid HTTP or HTTPS URL." }; if (title.length < 3 || title.length > 160) return { error: "Activity title must be between 3 and 160 characters." }; if (metaTitle.length > 160) return { error: "Meta title must be 160 characters or less." }; if (metaDescription.length > 320) return { error: "Meta description must be 320 characters or less." }; if (shortDescription.length < 10 || shortDescription.length > 240) return { error: "Short description must be between 10 and 240 characters." }; if (description.length < 20 || description.length > 5000) return { error: "Full description must be between 20 and 5000 characters." }; if (category.length < 2 || category.length > 100) return { error: "Enter a valid category." }; if (location.length < 2 || location.length > 160) return { error: "Enter a valid location." }; if (!isHttpUrl(affiliateUrl)) return { error: "Affiliate URL must be a valid HTTP or HTTPS URL." }; if (price === null) return { error: "Enter a valid activity price." }; if (!(AFFILIATE_CURRENCIES as readonly string[]).includes(currency)) return { error: "Select a valid currency." }; if (discountedPrice !== null && discountedPrice >= price) return { error: "Discounted price must be lower than the regular price." }; if (!types.length) return { error: "Select at least one activity type." };
  return { data: { slug, image, galleryImages, ogImage, title, metaTitle, metaDescription, shortDescription, description, category, location, affiliateUrl, price, currency, discountedPrice, types, featured, status } };
}
export async function getPublishedActivities(filters?: { q?: string; category?: string; location?: string; type?: string; featured?: boolean; limit?: number }) { await connectToDatabase(); await ensurePublishedActivitySlugs(); const query: Record<string, unknown> = { status: "published" }; const q = clean(filters?.q); const category = clean(filters?.category); const location = clean(filters?.location); const type = clean(filters?.type); if (q) query.title = { $regex: escapeRegex(q), $options: "i" }; if (category) query.category = category; if (location) query.location = location; if (type && (ACTIVITY_TYPES as readonly string[]).includes(type)) query.types = type; if (filters?.featured) query.featured = true; const activities = await Activity.find(query).sort({ featured: -1, createdAt: -1 }).limit(filters?.limit || 0).lean(); return serializeDocument(activities) as any[]; }
export async function getPublishedActivityBySlug(slug: string) { await connectToDatabase(); await ensurePublishedActivitySlugs(); const query = /^[a-f\d]{24}$/i.test(slug) ? { $or: [{ slug }, { _id: slug }], status: "published" } : { slug, status: "published" }; return serializeDocument(await Activity.findOne(query).lean()) as any | null; }
export async function getRelatedActivities(activity: any, limit = 3) { await connectToDatabase(); return serializeDocument(await Activity.find({ _id: { $ne: activity._id }, status: "published", $or: [{ category: activity.category }, { types: { $in: activity.types || [] } }] }).sort({ featured: -1, createdAt: -1 }).limit(limit).lean()) as any[]; }
export async function getActivityFilterOptions() { await connectToDatabase(); await ensurePublishedActivitySlugs(); const [categories, locations] = await Promise.all([Activity.distinct("category", { status: "published" }), Activity.distinct("location", { status: "published" })]); return { categories: categories.sort(), locations: locations.sort() }; }
export async function getActivitiesForAdmin() { await connectToDatabase(); return serializeDocument(await Activity.find({}).sort({ createdAt: -1 }).lean()) as any[]; }
