import { AFFILIATE_CURRENCIES, parseAffiliatePrice } from "@/lib/affiliate-price";
import { connectToDatabase } from "@/lib/db";
import { serializeDocument } from "@/lib/utils";
import AffiliateProduct from "@/models/AffiliateProduct";

type QuickInfo = { label: string; value: string };
export type AffiliateProductInput = { slug: string; title: string; description: string; shortDescription: string; metaTitle: string; metaDescription: string; ogImage: string; image: string; galleryImages: string[]; affiliateUrl: string; price: number; currency: string; discountedPrice: number | null; category: string; brand: string; location: string; productType: string; tags: string[]; badges: string[]; features: string[]; highlights: string[]; quickInfo: QuickInfo[]; featured: boolean; recommended: boolean; status: "draft" | "published" };
const clean = (value: unknown) => typeof value === "string" ? value.trim() : "";
const cleanList = (value: unknown, limit = 30) => Array.isArray(value) ? Array.from(new Set(value.map(clean).filter(Boolean))).slice(0, limit) : [];
const isHttpUrl = (value: string) => { try { return ["http:", "https:"].includes(new URL(value).protocol); } catch { return false; } };
const validImage = (value: string) => value.startsWith("/") || isHttpUrl(value);
const escapeRegex = (value: string) => value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
export function slugifyProduct(value: string) { return value.toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 100); }
let affiliateProductIndexSetup: Promise<void> | null = null;
export async function ensureAffiliateProductIndexes() {
  await connectToDatabase();
  affiliateProductIndexSetup ??= (async () => {
    try {
      await AffiliateProduct.collection.dropIndex("tags_1_badges_1_features_1_status_1");
    } catch (error) {
      const code = (error as { code?: number }).code;
      if (code !== 27) throw error;
    }
    await AffiliateProduct.createIndexes();
  })().catch((error) => { affiliateProductIndexSetup = null; throw error; });
  await affiliateProductIndexSetup;
}
async function ensurePublishedProductSlugs() { const missing = await AffiliateProduct.find({ status: "published", $or: [{ slug: { $exists: false } }, { slug: "" }] }).select("_id title").lean(); await Promise.all(missing.map((product: any) => AffiliateProduct.updateOne({ _id: product._id }, { $set: { slug: `${slugifyProduct(product.title) || "product"}-${String(product._id).slice(-6)}` } }))); }
export function validateAffiliateProductPayload(payload: unknown): { data: AffiliateProductInput } | { error: string } {
 const input = (payload || {}) as Record<string, unknown>; const title = clean(input.title); const slug = slugifyProduct(clean(input.slug) || title); const description = clean(input.description); const shortDescription = clean(input.shortDescription); const metaTitle = clean(input.metaTitle); const metaDescription = clean(input.metaDescription); const image = clean(input.image); const ogImage = clean(input.ogImage); const galleryImages = cleanList(input.galleryImages, 12); const affiliateUrl = clean(input.affiliateUrl); const price = parseAffiliatePrice(input.price); const currency = clean(input.currency) || "MAD"; const discountedPrice = parseAffiliatePrice(input.discountedPrice); const category = clean(input.category); const brand = clean(input.brand); const location = clean(input.location); const productType = clean(input.productType); const tags = cleanList(input.tags); const badges = cleanList(input.badges); const features = cleanList(input.features); const highlights = cleanList(input.highlights); const quickInfo = Array.isArray(input.quickInfo) ? input.quickInfo.map((item) => ({ label: clean((item as any)?.label), value: clean((item as any)?.value) })).filter((item) => item.label && item.value).slice(0, 12) : []; const featured = input.featured === true; const recommended = input.recommended === true; const status = input.status === "published" ? "published" : "draft";
 if (!slug) return { error: "Enter a valid product slug." }; if (title.length < 3 || title.length > 160) return { error: "Product title must be between 3 and 160 characters." }; if (description.length < 10 || description.length > 5000) return { error: "Product description must be between 10 and 5000 characters." }; if (shortDescription.length > 300 || metaDescription.length > 320 || metaTitle.length > 160) return { error: "SEO text exceeds its maximum length." }; if (!validImage(image) || (ogImage && !validImage(ogImage)) || galleryImages.some((item) => !validImage(item))) return { error: "All product images must use valid URLs." }; if (!isHttpUrl(affiliateUrl)) return { error: "Affiliate URL must be a valid HTTP or HTTPS URL." }; if (price === null) return { error: "Enter a valid product price." }; if (!(AFFILIATE_CURRENCIES as readonly string[]).includes(currency)) return { error: "Select a valid currency." }; if (discountedPrice !== null && discountedPrice >= price) return { error: "Discounted price must be lower than the regular price." };
 return { data: { slug, title, description, shortDescription, metaTitle, metaDescription, ogImage, image, galleryImages, affiliateUrl, price, currency, discountedPrice, category, brand, location, productType, tags, badges, features, highlights, quickInfo, featured, recommended, status } };
}
export async function getPublishedAffiliateProducts(filters?: { q?: string; category?: string; brand?: string; location?: string; tag?: string; badge?: string; feature?: string; sort?: string; featured?: boolean; recommended?: boolean; limit?: number }) { await ensureAffiliateProductIndexes(); await ensurePublishedProductSlugs(); const query: Record<string, unknown> = { status: "published" }; const q = clean(filters?.q); if (q) query.title = { $regex: escapeRegex(q), $options: "i" }; for (const key of ["category", "brand", "location"] as const) { const value = clean(filters?.[key]); if (value) query[key] = value; } if (clean(filters?.tag)) query.tags = clean(filters?.tag); if (clean(filters?.badge)) query.badges = clean(filters?.badge); if (clean(filters?.feature)) query.features = clean(filters?.feature); if (filters?.featured) query.featured = true; if (filters?.recommended) query.recommended = true; const sort: Record<string, 1 | -1> = filters?.sort === "popular" ? { viewCount: -1 as const, clickCount: -1 as const } : filters?.sort === "featured" ? { featured: -1 as const, createdAt: -1 as const } : { createdAt: -1 as const }; return serializeDocument(await AffiliateProduct.find(query).sort(sort).limit(filters?.limit || 0).lean()) as any[]; }
export async function getPublishedAffiliateProductBySlug(slug: string) { await ensureAffiliateProductIndexes(); await ensurePublishedProductSlugs(); const query = /^[a-f\d]{24}$/i.test(slug) ? { $or: [{ slug }, { _id: slug }], status: "published" } : { slug, status: "published" }; return serializeDocument(await AffiliateProduct.findOne(query).lean()) as any | null; }
export async function getRelatedAffiliateProducts(product: any, limit = 4) { await ensureAffiliateProductIndexes(); return serializeDocument(await AffiliateProduct.find({ _id: { $ne: product._id }, status: "published", $or: [{ category: product.category }, { brand: product.brand }, { productType: product.productType }, { tags: { $in: product.tags || [] } }] }).sort({ featured: -1, viewCount: -1 }).limit(limit).lean()) as any[]; }
export async function getAffiliateProductFilterOptions() { await ensureAffiliateProductIndexes(); const [categories, brands, locations, tags, badges, features] = await Promise.all(["category", "brand", "location", "tags", "badges", "features"].map((field) => AffiliateProduct.distinct(field, { status: "published" }))); return { categories: categories.filter(Boolean).sort() as string[], brands: brands.filter(Boolean).sort() as string[], locations: locations.filter(Boolean).sort() as string[], tags: tags.filter(Boolean).sort() as string[], badges: badges.filter(Boolean).sort() as string[], features: features.filter(Boolean).sort() as string[] }; }
export async function getAffiliateProductsForAdmin() { await ensureAffiliateProductIndexes(); return serializeDocument(await AffiliateProduct.find({}).sort({ createdAt: -1 }).lean()) as any[]; }
