import crypto from "node:crypto";
import dns from "node:dns/promises";
import { connectToDatabase } from "@/lib/db";
import { slugifyProduct } from "@/lib/affiliate-products";
import ResellingProduct from "@/models/ResellingProduct";
import MarketplaceSyncLog from "@/models/MarketplaceSyncLog";
import { revalidatePath } from "next/cache";

export type SupplierName = "jumia";
export type NormalizedVariant = { name: string; value: string; price?: number | null; stockStatus?: string; stockQuantity?: number | null };
export type NormalizedProduct = { supplier: SupplierName; sourceUrl: string; canonicalUrl: string; sourceProductId: string; title: string; description: string; shortDescription: string; brand: string; model: string; sku: string; category: string; sourcePrice: number | null; originalPrice: number | null; currency: string; stockStatus: "in_stock" | "out_of_stock" | "unknown"; stockQuantity: number | null; variants: NormalizedVariant[]; specifications: Record<string,string>; images: string[]; extractionMetadata: { strategy: string[]; fetchedAt: string }; sourceHash: string };
const MAX_HTML = 5_000_000;
const MAX_IMAGES = 20;
const FETCH_TIMEOUT = 20_000;
const PRIVATE_HOSTS = new Set(["localhost", "localhost.localdomain", "metadata.google.internal", "metadata"]);
const clean = (value: unknown) => typeof value === "string" ? decodeHtml(value.replace(/\s+/g, " ").trim()) : "";
function decodeHtml(value: string) { return value.replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,"<").replace(/&gt;/gi,">"); }
function numberFrom(value: unknown): number | null { if(typeof value === "number"&&Number.isFinite(value))return value; const text=clean(value).replace(/\s/g,"").replace(/[^\d,.-]/g,""); if(!text)return null; const normalized=text.includes(",")&&text.includes(".")?text.replace(/\./g,"").replace(",","."):text.replace(",","."); const n=Number(normalized); return Number.isFinite(n)?n:null; }
function absoluteUrl(value:string,base:URL){try{const url=new URL(value,base);return ["https:","http:"].includes(url.protocol)?url.toString():"";}catch{return "";}}
function normalizeSourceUrl(input:string){const url=new URL(input);url.hash="";for(const key of [...url.searchParams.keys()])if(/^(utm_|fbclid|gclid|ref|source|campaign|aff|affiliate)/i.test(key))url.searchParams.delete(key);return url.toString();}
async function assertPublicUrl(input:string){const url=new URL(input);if(!["http:","https:"].includes(url.protocol))throw new Error("Only HTTP and HTTPS URLs are supported.");if(url.username||url.password)throw new Error("URLs with embedded credentials are not allowed.");const hostname=url.hostname.toLowerCase();if(PRIVATE_HOSTS.has(hostname)||hostname.endsWith(".local")||hostname==="0.0.0.0"||hostname==="169.254.169.254")throw new Error("The supplied URL is not a public URL.");if(/^\d+\.\d+\.\d+\.\d+$/.test(hostname)){const[a,b,c,d]=hostname.split(".").map(Number);if(a===10||a===127||a===0||(a===169&&b===254)||(a===192&&b===168)||(a===172&&b>=16&&b<=31))throw new Error("The supplied URL targets a private network.");}const addresses=await dns.lookup(hostname,{all:true});for(const address of addresses){const ip=address.address;if(ip==="::1"||ip.startsWith("fc")||ip.startsWith("fd")||ip.startsWith("fe80:")||ip.startsWith("::ffff:10.")||ip.startsWith("::ffff:192.168."))throw new Error("The supplied URL targets a private network.");if(/^\d+\.\d+\.\d+\.\d+$/.test(ip)){const[a,b]=ip.split(".").map(Number);if(a===10||a===127||a===0||(a===169&&b===254)||(a===192&&b===168)||(a===172&&b>=16&&b<=31))throw new Error("The supplied URL targets a private network.");}}return url;}
async function fetchPublicPage(input:string){let current=await assertPublicUrl(input);for(let i=0;i<4;i++){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),FETCH_TIMEOUT);try{const response=await fetch(current,{method:"GET",redirect:"manual",signal:controller.signal,headers:{"user-agent":"Mozilla/5.0 (compatible; MoroccanTripProductImporter/1.0)",accept:"text/html,application/xhtml+xml"},cache:"no-store"});if(response.status>=300&&response.status<400){const location=response.headers.get("location");if(!location)throw new Error(`Source returned redirect ${response.status} without a location.`);current=await assertPublicUrl(new URL(location,current).toString());continue;}if(!response.ok){if([401,403,429].includes(response.status))throw Object.assign(new Error("Source blocked automated access."),{code:"blocked"});throw new Error(`Source returned HTTP ${response.status}.`);}const text=await response.text();if(!text||text.length>MAX_HTML)throw new Error("Source page is empty or too large.");return{html:text,finalUrl:current.toString()};}finally{clearTimeout(timer);}}throw new Error("Too many source redirects.");}
function jsonLdBlocks(html:string){const blocks:any[]=[];for(const match of html.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)){try{const parsed=JSON.parse(match[1].trim());if(Array.isArray(parsed))blocks.push(...parsed);else if(parsed&&Array.isArray(parsed["@graph"]))blocks.push(...parsed["@graph"]);else blocks.push(parsed);}catch{}}return blocks;}
function meta(html:string,key:string,attr="property"){const escaped=key.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");const re=new RegExp(`<meta[^>]+${attr}=["']${escaped}["'][^>]+content=["']([^"']+)["'][^>]*>`,"i");return clean(html.match(re)?.[1]||"");}
function metaAny(html:string,keys:string[]){for(const key of keys){const value=meta(html,key,"property")||meta(html,key,"name");if(value)return value;}return "";}
function textSelector(html:string,selector:RegExp){return clean(html.match(selector)?.[1]||"");}
function findProductJson(blocks:any[]){return blocks.find(item=>{const type=item?.["@type"];return type==="Product"||(Array.isArray(type)&&type.includes("Product"));})||{};}
function extractOffers(product:any){const offer=Array.isArray(product.offers)?product.offers[0]:product.offers||{};const price=numberFrom(offer.price??product.price);const high=numberFrom(offer.highPrice);const low=numberFrom(offer.lowPrice);return{price:price??low,originalPrice:high&&price&&high>price?high:null,currency:clean(offer.priceCurrency||product.priceCurrency)||"MAD",availability:clean(offer.availability||product.availability)};}
function stockFrom(value:string){const v=value.toLowerCase();if(/outofstock|out of stock|rupture|indisponible|épuisé|غير متوفر/.test(v))return"out_of_stock" as const;if(/instock|in stock|en stock|disponible|متوفر/.test(v))return"in_stock" as const;return"unknown" as const;}
function extractImages(product:any,base:URL,html:string){const values=[...(Array.isArray(product.image)?product.image:[product.image]),metaAny(html,["og:image","twitter:image"])].map(value=>absoluteUrl(clean(value),base)).filter(Boolean);return Array.from(new Set(values)).slice(0,MAX_IMAGES);}
function extractSpecifications(product:any){const source=product.additionalProperty||product.specifications||{};const out:Record<string,string>={};if(Array.isArray(source)){for(const item of source){const key=clean(item?.name),value=clean(item?.value);if(key&&value)out[key]=value;}}else if(source&&typeof source==="object"){for(const[key,value]of Object.entries(source)){const v=clean(value);if(v)out[clean(key)]=v;}}return Object.fromEntries(Object.entries(out).slice(0,50));}
function extractVariants(product:any):NormalizedVariant[]{const candidates=Array.isArray(product.hasVariant)?product.hasVariant:Array.isArray(product.variants)?product.variants:[];return candidates.slice(0,100).map((item:any)=>({name:clean(item?.name||item?.color||item?.size||"Variant"),value:clean(item?.value||item?.color||item?.size||item?.sku),price:numberFrom(item?.offers?.price??item?.price),stockStatus:stockFrom(clean(item?.offers?.availability||item?.availability)),stockQuantity:numberFrom(item?.inventoryLevel?.value??item?.stockQuantity)})).filter(item=>item.name&&item.value);}
function sourceIdFrom(url:string,product:any){const explicit=clean(product.sku||product.productID||product.mpn);if(explicit)return explicit;const match=url.match(/(?:^|[-_.\/])(\d{6,})(?:\.html)?(?:$|[-_.\/?])/i);return match?.[1]||"";}
function stablePayload(product:NormalizedProduct){return JSON.stringify({title:product.title,description:product.description,shortDescription:product.shortDescription,brand:product.brand,model:product.model,sku:product.sku,sourcePrice:product.sourcePrice,originalPrice:product.originalPrice,currency:product.currency,stockStatus:product.stockStatus,stockQuantity:product.stockQuantity,variants:product.variants,specifications:product.specifications,images:product.images});}
const hash=(value:string)=>crypto.createHash("sha256").update(value).digest("hex");
export async function extractJumiaProduct(inputUrl:string):Promise<NormalizedProduct>{const normalizedInput=normalizeSourceUrl(inputUrl);const{html,finalUrl}=await fetchPublicPage(normalizedInput);const base=new URL(finalUrl);const blocks=jsonLdBlocks(html);const product=findProductJson(blocks);const strategies:string[]=[];if(Object.keys(product).length)strategies.push("json-ld");const title=clean(product.name)||metaAny(html,["og:title","twitter:title"])||textSelector(html,/<h1[^>]*>([\s\S]*?)<\/h1>/i)||clean(html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]);const description=clean(product.description)||metaAny(html,["og:description","description"])||textSelector(html,/<div[^>]+(?:id|class)=["'][^"']*(?:description|product-description)[^"']*["'][^>]*>([\s\S]*?)<\/div>/i);const shortDescription=clean(product.shortDescription)||metaAny(html,["og:description"]);const offers=extractOffers(product);const brand=clean(typeof product.brand==="object"?product.brand?.name:product.brand)||textSelector(html,/(?:brand|marque)[^<]{0,80}<[^>]*>([^<]+)/i);const model=clean(product.model||product.mpn);const sku=clean(product.sku||product.mpn);const category=clean(product.category)||textSelector(html,/(?:category|catégorie)[^<]{0,80}<[^>]*>([^<]+)/i);const images=extractImages(product,base,html);if(images.length)strategies.push("metadata/images");if(title||description||offers.price!==null)strategies.push("html-fallback");const availability=offers.availability||clean(product.availability);const stockStatus=stockFrom(availability);const specs=extractSpecifications(product);const variants=extractVariants(product);const sourceProductId=sourceIdFrom(finalUrl,product);if(!title||title.length<3)throw new Error("Product title could not be extracted.");if(!images[0])throw new Error("No usable product image could be extracted.");if(offers.price===null)throw new Error("Product price could not be extracted.");const normalized:NormalizedProduct={supplier:"jumia",sourceUrl:normalizedInput,canonicalUrl:clean(product.url)?absoluteUrl(clean(product.url),base)||finalUrl:finalUrl,sourceProductId,title,description:description||title,shortDescription:shortDescription||description.slice(0,280),brand,model,sku,category,sourcePrice:offers.price,originalPrice:offers.originalPrice,currency:offers.currency||"MAD",stockStatus,stockQuantity:null,variants,specifications:specs,images,extractionMetadata:{strategy:strategies,fetchedAt:new Date().toISOString()},sourceHash:""};normalized.sourceHash=hash(stablePayload(normalized));return normalized;}
export function validateSupplierUrl(input:string){const url=new URL(input);const host=url.hostname.toLowerCase();if(host!=="www.jumia.ma"&&host!=="jumia.ma")throw new Error("This importer currently supports Jumia Morocco only.");if(!/^\/[^?]*\.html$/i.test(url.pathname))throw new Error("Enter a Jumia Morocco product URL.");return normalizeSourceUrl(input);}
async function uploadSourceImage(sourceUrl:string,fingerprint:string){const cloudName=process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME;const uploadPreset=process.env.NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET;if(!cloudName||!uploadPreset)throw new Error("Cloudinary is not configured.");const response=await fetch(sourceUrl,{cache:"no-store",headers:{"user-agent":"Mozilla/5.0 (compatible; MoroccanTripProductImporter/1.0)"}});if(!response.ok)throw new Error("Could not download a source product image.");const bytes=await response.arrayBuffer();if(bytes.byteLength>8000000)throw new Error("Source image is too large.");const form=new FormData();form.append("file",new Blob([bytes],{type:response.headers.get("content-type")||"image/jpeg"}),`source-${fingerprint}.jpg`);form.append("upload_preset",uploadPreset);form.append("folder","moroccantrip/marketplace/imported");const upload=await fetch(`https://api.cloudinary.com/v1_1/${cloudName}/image/upload`,{method:"POST",body:form});const data=await upload.json();if(!upload.ok||typeof data?.secure_url!=="string")throw new Error("Cloudinary image upload failed.");return data.secure_url as string;}
async function cloudinaryImages(sourceImages:string[],previous:any[]){const previousByFingerprint=new Map((previous||[]).map(item=>[item.fingerprint,item.cloudinaryUrl]));const output:Array<{sourceUrl:string;fingerprint:string;cloudinaryUrl:string}>=[];for(const sourceUrl of sourceImages.slice(0,MAX_IMAGES)){try{await assertPublicUrl(sourceUrl);const response=await fetch(sourceUrl,{cache:"no-store",headers:{"user-agent":"Mozilla/5.0 (compatible; MoroccanTripProductImporter/1.0)"}});if(!response.ok)continue;const bytes=Buffer.from(await response.arrayBuffer());if(bytes.byteLength>8000000)continue;const fingerprint=crypto.createHash("sha256").update(bytes).digest("hex");const existing=previousByFingerprint.get(fingerprint);const cloudinaryUrl=existing||await uploadSourceImage(sourceUrl,fingerprint);output.push({sourceUrl,fingerprint,cloudinaryUrl});}catch{}}if(!output.length)throw new Error("No source image could be imported into Cloudinary.");return output;}
function localized(value:string){return{ar:value,fr:value,en:value};}
function sourceVariants(next:NormalizedProduct){const groups=new Map<string,string[]>();for(const variant of next.variants){const values=groups.get(variant.name)||[];if(variant.value&&!values.includes(variant.value))values.push(variant.value);groups.set(variant.name,values);}return Array.from(groups.entries()).map(([name,options])=>({name,options}));}
function sourceSpecifications(next:NormalizedProduct){return Object.entries(next.specifications).map(([label,value])=>({label,value}));}
function publicChanges(oldProduct:any,next:NormalizedProduct){const pairs:Array<[string,unknown,unknown]>=[["title",oldProduct.title?.en,next.title],["description",oldProduct.description?.en,next.description],["brand",oldProduct.brand,next.brand],["sourcePrice",oldProduct.sourceSync?.sourcePrice,next.sourcePrice],["originalPrice",oldProduct.sourceSync?.originalPrice,next.originalPrice],["stockStatus",oldProduct.sourceSync?.stockStatus,next.stockStatus],["variants",oldProduct.sourceSync?.variants||[],next.variants],["specifications",oldProduct.sourceSync?.specifications||{},next.specifications],["images",oldProduct.sourceSync?.images?.map((x:any)=>x.sourceUrl)||[],next.images]];return pairs.filter(([,a,b])=>JSON.stringify(a)!==JSON.stringify(b)).map(([field,oldValue,newValue])=>({field,oldValue,newValue}));}
function sellingPrice(next:NormalizedProduct,product:any){if(product.sourceSync?.pricingMode==="manual")return product.sellingPrice;const margin=Number(product.sourceSync?.marginPercent??30);return Math.max(0,Math.round((Number(next.sourcePrice||0)*(1+margin/100))*100)/100);}
async function applyNormalizedProduct(product:any,next:NormalizedProduct,mode:"create"|"sync"){const previousImages=product?.sourceSync?.images||[];const importedImages=await cloudinaryImages(next.images,previousImages);const imageUrls=importedImages.map(item=>item.cloudinaryUrl);const changes=mode==="sync"?publicChanges(product,next):[];const protectedFields=new Set(product?.sourceSync?.manualOverrides||[]);const set:Record<string,unknown>={"sourceSync.sourcePrice":next.sourcePrice,"sourceSync.originalPrice":next.originalPrice,"sourceSync.currency":next.currency,sourcePrice:next.sourcePrice,sourceCurrency:next.currency,"sourceSync.stockStatus":next.stockStatus,"sourceSync.stockQuantity":next.stockQuantity,"sourceSync.variants":next.variants,"sourceSync.specifications":next.specifications,"sourceSync.images":importedImages,"sourceSync.sourceHash":next.sourceHash,"sourceSync.lastSuccessfulSyncAt":new Date(),"sourceSync.lastSyncAttemptAt":new Date(),"sourceSync.lastSyncStatus":"synced","sourceSync.lastSyncError":"","sourceSync.nextSyncAt":new Date(Date.now()+Number(product?.sourceSync?.syncIntervalMinutes||60)*3600000)};if(!protectedFields.has("title")){set.title=localized(next.title);set.shortDescription=localized(next.shortDescription);}if(!protectedFields.has("description"))set.description=localized(next.description);if(!protectedFields.has("brand"))set.brand=next.brand;if(!protectedFields.has("category"))set.category=next.category;if(!protectedFields.has("sku"))set.sku=next.sku;if(!protectedFields.has("images")){set.mainImage=imageUrls[0];set.images=imageUrls;set.ogImage=imageUrls[0];}if(!protectedFields.has("variants"))set.variants=sourceVariants(next);if(!protectedFields.has("specifications"))set.specifications=sourceSpecifications(next);if(!protectedFields.has("sellingPrice"))set.sellingPrice=sellingPrice(next,product);if(!protectedFields.has("margin"))set.estimatedProfit=Math.max(0,Number(set.sellingPrice??product.sellingPrice)-Number(next.sourcePrice||0));if(next.stockStatus==="out_of_stock")set.stockStatus="out_of_stock";else if(next.stockStatus==="in_stock"&&!protectedFields.has("stockStatus"))set.stockStatus="available";if(mode==="sync")await ResellingProduct.updateOne({_id:product._id},{$set:set});return{changes,imageUrls};}
export async function importProductFromUrl(inputUrl:string){const url=validateSupplierUrl(inputUrl);const next=await extractJumiaProduct(url);await connectToDatabase();const identity=next.sourceProductId?{"sourceSync.enabled":true,"sourceSync.supplier":next.supplier,"sourceSync.sourceProductId":next.sourceProductId}:{"sourceSync.enabled":true,"sourceSync.supplier":next.supplier,"sourceSync.canonicalUrl":next.canonicalUrl};const existing=await ResellingProduct.findOne(identity).lean();if(existing)return{duplicate:true,existing:existing as any,product:next};const imageRecords=await cloudinaryImages(next.images,[]);const imageUrls=imageRecords.map(item=>item.cloudinaryUrl);const margin=30;const price=Math.max(0,Math.round(Number(next.sourcePrice||0)*1.3*100)/100);const slugBase=slugifyProduct(next.title)||"imported-product";const slug=`${slugBase}-${next.sourceProductId||crypto.randomBytes(3).toString("hex")}`.slice(0,110);const product=await ResellingProduct.create({title:localized(next.title),slug,description:localized(next.description),shortDescription:localized(next.shortDescription),images:imageUrls,mainImage:imageUrls[0],category:next.category,subcategory:"",brand:next.brand,sku:next.sku,variants:sourceVariants(next),specifications:sourceSpecifications(next),sourceProvider:next.supplier,sourceUrl:next.sourceUrl,sourceProductId:next.sourceProductId,sourcePrice:next.sourcePrice,sourceCurrency:next.currency,sellingPrice:price,marginType:"percentage",marginValue:margin,estimatedProfit:Math.max(0,price-Number(next.sourcePrice||0)),shippingInfo:localized("Cash on delivery available"),stockStatus:next.stockStatus==="out_of_stock"?"out_of_stock":next.stockStatus==="in_stock"?"available":"check_availability",badges:[],featured:false,status:"draft",metaTitle:localized(next.title.slice(0,160)),metaDescription:localized(next.shortDescription.slice(0,320)),ogImage:imageUrls[0],sourceSync:{enabled:true,supplier:next.supplier,sourceUrl:next.sourceUrl,canonicalUrl:next.canonicalUrl,sourceProductId:next.sourceProductId,sourceHash:next.sourceHash,sourcePrice:next.sourcePrice,originalPrice:next.originalPrice,currency:next.currency,stockStatus:next.stockStatus,stockQuantity:next.stockQuantity,variants:next.variants,specifications:next.specifications,images:imageRecords,pricingMode:"margin",marginPercent:margin,manualOverrides:[],syncIntervalMinutes:60,lastSyncAttemptAt:new Date(),lastSuccessfulSyncAt:new Date(),lastSyncStatus:"synced",lastSyncError:"",nextSyncAt:new Date(Date.now()+3600000)}});await MarketplaceSyncLog.create({productId:product._id,supplier:next.supplier,sourceUrl:next.sourceUrl,status:"success",changedFields:[],changes:[],durationMs:0});return{duplicate:false,existing:null,product:product.toObject(),extracted:next};}
export async function syncImportedProduct(productId:string){const started=Date.now();await connectToDatabase();const product=await ResellingProduct.findById(productId);if(!product||!product.sourceSync?.enabled)throw new Error("This product is not configured for source synchronization.");const lockUntil=new Date(Date.now()+300000);const locked=await ResellingProduct.findOneAndUpdate({_id:productId,"sourceSync.enabled":true,$or:[{"sourceSync.lockedUntil":{$exists:false}},{"sourceSync.lockedUntil":{$lt:new Date()}}]},{$set:{"sourceSync.lockedUntil":lockUntil,"sourceSync.lastSyncAttemptAt":new Date(),"sourceSync.lastSyncStatus":"syncing"}},{new:true});if(!locked)return{status:"busy" as const};try{const next=await extractJumiaProduct(product.sourceSync.sourceUrl);if(next.sourceHash===product.sourceSync.sourceHash){await ResellingProduct.updateOne({_id:productId},{$set:{"sourceSync.lastSuccessfulSyncAt":new Date(),"sourceSync.lastSyncStatus":"synced","sourceSync.lastSyncError":"","sourceSync.nextSyncAt":new Date(Date.now()+Number(product.sourceSync.syncIntervalMinutes||60)*3600000),"sourceSync.lockedUntil":null}});await MarketplaceSyncLog.create({productId,supplier:next.supplier,sourceUrl:next.sourceUrl,status:"unchanged",changedFields:[],changes:[],durationMs:Date.now()-started});return{status:"unchanged" as const,changes:[]};}const changes=publicChanges(product.toObject(),next);await applyNormalizedProduct(product.toObject(),next,"sync");await MarketplaceSyncLog.create({productId,supplier:next.supplier,sourceUrl:next.sourceUrl,status:"success",changedFields:changes.map(x=>x.field),changes,durationMs:Date.now()-started});revalidatePath("/marketplace");revalidatePath(`/marketplace/${product.slug}`);revalidatePath(`/fr/marketplace/${product.slug}`);revalidatePath(`/ar/marketplace/${product.slug}`);await ResellingProduct.updateOne({_id:productId},{$set:{"sourceSync.lastSyncStatus":changes.length?"changed":"synced","sourceSync.lockedUntil":null}});return{status:"success" as const,changes};}catch(error){const message=error instanceof Error?error.message:"Source synchronization failed.";const status=(error as any)?.code==="blocked"?"blocked":"error";await ResellingProduct.updateOne({_id:productId},{$set:{"sourceSync.lastSyncStatus":status,"sourceSync.lastSyncError":message,"sourceSync.lockedUntil":null}});await MarketplaceSyncLog.create({productId,supplier:product.sourceSync.supplier,sourceUrl:product.sourceSync.sourceUrl,status,changedFields:[],changes:[],error:message,durationMs:Date.now()-started});return{status:status as "error"|"blocked",error:message,changes:[]};}}
export async function syncDueImportedProducts(limit=10){await connectToDatabase();const products=await ResellingProduct.find({"sourceSync.enabled":true,"sourceSync.nextSyncAt":{$lte:new Date()},$or:[{"sourceSync.lockedUntil":{$exists:false}},{"sourceSync.lockedUntil":{$lt:new Date()}}]}).select("_id").limit(Math.max(1,Math.min(limit,50))).lean();const results=[];for(const product of products)results.push({id:String(product._id),...(await syncImportedProduct(String(product._id)))});return results;}
