function metaAny(html:string,keys:string[]){for(const key of keys){const value=meta(html,key,"property")||meta(html,key,"name");if(value)return value;}return "";}
function textSelector(html:string,selector:RegExp){return clean(html.match(selector)?.[1]||"");}
function findProductJson(blocks:any[]){return blocks.find(item=>{const type=item?.["@type"];return type==="Product"||(Array.isArray(type)&&type.includes("Product"));})||{};}
function extractOffers(product:any){const offer=Array.isArray(product.offers)?product.offers[0]:product.offers||{};const price=numberFrom(offer.price??product.price);const high=numberFrom(offer.highPrice);const low=numberFrom(offer.lowPrice);return{price:price??low,originalPrice:high&&price&&high>price?high:null,currency:clean(offer.priceCurrency||product.priceCurrency)||"MAD",availability:clean(offer.availability||product.availability)};}
function stockFrom(value:string){const v=value.toLowerCase();if(/outofstock|out of stock|rupture|indisponible|épuisé|غير متوفر/.test(v))return"out_of_stock" as const;if(/instock|in stock|en stock|disponible|متوفر/.test(v))return"in_stock" as const;return"unknown" as const;}
function extractImages(product:any,base:URL,html:string){const values=[...(Array.isArray(product.image)?product.image:[product.image]),metaAny(html,["og:image","twitter:image"])].map(value=>absoluteUrl(clean(value),base)).filter(Boolean);return Array.from(new Set(values)).slice(0,MAX_IMAGES);}
function extractSpecifications(product:any){const source=product.additionalProperty||product.specifications||{};const out:Record<string,string>={};if(Array.isArray(source)){for(const item of source){const key=clean(item?.name),value=clean(item?.value);if(key&&value)out[key]=value;}}else if(source&&typeof source==="object"){for(const[key,value]of Object.entries(source)){const v=clean(value);if(v)out[clean(key)]=v;}}return Object.fromEntries(Object.entries(out).slice(0,50));}
function extractVariants(product:any):NormalizedVariant[]{const candidates=Array.isArray(product.hasVariant)?product.hasVariant:Array.isArray(product.variants)?product.variants:[];return candidates.slice(0,100).map((item:any):NormalizedVariant=>({name:clean(item?.name||item?.color||item?.size||"Variant"),value:clean(item?.value||item?.color||item?.size||item?.sku),price:numberFrom(item?.offers?.price??item?.price),stockStatus:stockFrom(clean(item?.offers?.availability||item?.availability)),stockQuantity:numberFrom(item?.inventoryLevel?.value??item?.stockQuantity)})).filter((item:NormalizedVariant)=>item.name&&item.value);}
function sourceIdFrom(url:string,product:any){const explicit=clean(product.sku||product.productID||product.mpn);if(explicit)return explicit;const match=url.match(/(?:^|[-_.\/])(\d{6,})(?:\.html)?(?:$|[-_.\/?])/i);return match?.[1]||"";}
function stablePayload(product:NormalizedProduct){return JSON.stringify({title:product.title,description:product.description,shortDescription:product.shortDescription,brand:product.brand,model:product.model,sku:product.sku,sourcePrice:product.sourcePrice,originalPrice:product.originalPrice,currency:product.currency,stockStatus:product.stockStatus,stockQuantity:product.stockQuantity,variants:product.variants,specifications:product.specifications,images:product.images});}
const hash=(value:string)=>crypto.createHash("sha256").update(value).digest("hex");