import ResellingProduct from "@/models/ResellingProduct";
import ResellingOrder from "@/models/ResellingOrder";
import { connectToDatabase } from "@/lib/db";
import { serializeDocument } from "@/lib/utils";
import { makeVariantId, normalizeStoredVariants, parseEncodedVariant, isVariantInStock, type VariantOptions } from "@/lib/reselling-variants";

export const SUPPORTED_SOURCE_PROVIDERS = ["jumia", "temu", "aliexpress", "other"] as const;
export type SourceProvider = typeof SUPPORTED_SOURCE_PROVIDERS[number];
export type ProductStatus = "draft" | "published" | "out_of_stock" | "archived";
const clean = (v: unknown) => typeof v === "string" ? v.trim() : "";
const list = (v: unknown, max = 30) => Array.isArray(v) ? Array.from(new Set(v.map(clean).filter(Boolean))).slice(0, max) : [];
export function slugifyResellingProduct(v: string) { return v.toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 100); }
function localized(v: unknown) { if (typeof v === "string") return { ar: v.trim(), fr: v.trim(), en: v.trim() }; const x = (v || {}) as any; return { ar: clean(x.ar), fr: clean(x.fr), en: clean(x.en) }; }
function validHttp(v: string) { try { const u = new URL(v); return u.protocol === "https:"; } catch { return false; } }
function safeSourceUrl(v: string) { if (!v) return ""; if (!validHttp(v)) return ""; try { const host = new URL(v).hostname.toLowerCase(); return ["jumia.ma", "www.jumia.ma", "temu.com", "www.temu.com", "aliexpress.com", "www.aliexpress.com"].some(d => host === d || host.endsWith(`.${d}`)) ? v : ""; } catch { return ""; } }
export function calculatePricing(sourcePrice: number, marginType: "fixed" | "percentage", marginValue: number) { const source = Math.max(0, Number(sourcePrice) || 0); const margin = Math.max(0, Number(marginValue) || 0); const profit = marginType === "percentage" ? source * margin / 100 : margin; return { sellingPrice: Math.round((source + profit) * 100) / 100, estimatedProfit: Math.round(profit * 100) / 100 }; }
export function validateResellingProductPayload(payload: unknown) { const x = (payload || {}) as any; const title = localized(x.title); const description = localized(x.description); const shortDescription = localized(x.shortDescription); const slug = slugifyResellingProduct(clean(x.slug) || title.en || title.fr || title.ar); const sourceProvider = clean(x.sourceProvider) || "manual"; const sourceUrl = safeSourceUrl(clean(x.sourceUrl)); const sourcePrice = Math.max(0, Number(x.sourcePrice) || 0); const marginType = x.marginType === "percentage" ? "percentage" : "fixed"; const marginValue = Math.max(0, Number(x.marginValue) || 0); const pricing = calculatePricing(sourcePrice, marginType, marginValue); const sellingPrice = Number(x.sellingPrice) > 0 ? Number(x.sellingPrice) : pricing.sellingPrice; const mainImage = clean(x.mainImage); const images = list(x.images, 20); if (!slug) return { error: "A valid product title or slug is required." }; if (!title.ar || !title.fr || !title.en) return { error: "Product title is required in Arabic, French and English." }; if (!description.en && !description.fr && !description.ar) return { error: "Product description is required." }; if (!mainImage || !/^https?:\/\//i.test(mainImage)) return { error: "A valid main image URL is required." }; if (sourceUrl && sourceProvider === "manual") return { error: "Select the source provider for this URL." }; if (!sellingPrice || sellingPrice < 0) return { error: "Enter a valid selling price." }; return { data: { title, slug, description, shortDescription, images, mainImage, category: clean(x.category), subcategory: clean(x.subcategory), brand: clean(x.brand), sku: clean(x.sku), variants: Array.isArray(x.variants) ? x.variants : [], specifications: Array.isArray(x.specifications) ? x.specifications : [], sourceProvider, sourceUrl, sourceProductId: clean(x.sourceProductId), sourcePrice, sourceCurrency: clean(x.sourceCurrency) || "MAD", sellingPrice, marginType, marginValue, estimatedProfit: Math.max(0, sellingPrice - sourcePrice), shippingInfo: localized(x.shippingInfo), stockStatus: ["available", "limited", "out_of_stock", "check_availability"].includes(x.stockStatus) ? x.stockStatus : "check_availability", badges: list(x.badges, 10), featured: x.featured === true, status: (x.status === "published" || x.status === "out_of_stock" || x.status === "archived") ? x.status : "draft", metaTitle: localized(x.metaTitle), metaDescription: localized(x.metaDescription), ogImage: clean(x.ogImage) } }; }
export function parseSupplierUrl(rawUrl: string) { const url = clean(rawUrl); if (!validHttp(url)) return { error: "Use a secure HTTPS supplier URL." }; const host = new URL(url).hostname.toLowerCase(); let provider: SourceProvider | null = null; if (host === "jumia.ma" || host.endsWith(".jumia.ma")) provider = "jumia"; else if (host === "temu.com" || host.endsWith(".temu.com")) provider = "temu"; else if (host === "aliexpress.com" || host.endsWith(".aliexpress.com")) provider = "aliexpress"; if (!provider) return { error: "This supplier is not supported yet. Use manual entry instead." }; const parts = new URL(url).pathname.split("/").filter(Boolean); const sourceProductId = parts[parts.length - 1] || ""; return { provider, sourceProductId, sourceUrl: url, mode: "manual_review" as const }; }
export async function getPublishedResellingProducts(filters?: { q?: string; category?: string; brand?: string; sort?: string; limit?: number }) { await connectToDatabase(); const query: any = { status: "published" }; if (filters?.q) query.$or = [{ "title.en": { $regex: filters.q, $options: "i" } }, { "title.fr": { $regex: filters.q, $options: "i" } }, { "title.ar": { $regex: filters.q, $options: "i" } }]; if (filters?.category) query.category = filters.category; if (filters?.brand) query.brand = filters.brand; const sort: { featured: -1; createdAt: -1 } = { featured: -1, createdAt: -1 }; return serializeDocument(await ResellingProduct.find(query).select("title slug description shortDescription images mainImage category subcategory brand variants specifications sellingPrice sourcePrice sourceCurrency marginType marginValue shippingInfo stockStatus badges featured status createdAt").sort(sort).limit(filters?.limit || 0).lean()) as any[]; }
export async function getPublishedResellingProductBySlug(slug: string) { await connectToDatabase(); return serializeDocument(await ResellingProduct.findOne({ slug, status: "published" }).select("title slug description shortDescription images mainImage category subcategory brand sku variants specifications sellingPrice sourcePrice sourceCurrency marginType marginValue shippingInfo stockStatus badges featured status metaTitle metaDescription ogImage").lean()) as any | null; }
export async function getResellingProductsForAdmin() { await connectToDatabase(); return serializeDocument(await ResellingProduct.find({}).sort({ createdAt: -1 }).lean()) as any[]; }
export async function getResellingOrdersForAdmin() { await connectToDatabase(); return serializeDocument(await ResellingOrder.find({}).sort({ createdAt: -1 }).lean()) as any[]; }
export async function getResellingDashboardStats() { await connectToDatabase(); const [products, pending, orders, sales] = await Promise.all([ResellingProduct.countDocuments({ status: "published" }), ResellingOrder.countDocuments({ status: "pending" }), ResellingOrder.countDocuments({}), ResellingOrder.aggregate([{ $match: { status: { $ne: "cancelled" } } }, { $group: { _id: null, total: { $sum: "$totalAmount" }, profit: { $sum: "$profitSnapshot" } } }])]); const counts = await ResellingOrder.aggregate([{ $group: { _id: "$status", count: { $sum: 1 } } }]); return { products, pending, orders, sales: sales[0]?.total || 0, profit: sales[0]?.profit || 0, statusCounts: Object.fromEntries(counts.map((x: any) => [x._id, x.count])) }; }

function resolveSubmittedVariant(product: any, input: any) {
  const variants = normalizeStoredVariants(product.variants);
  if (!variants.length) return { variant: null, selectedOptions: {}, unitPrice: Number(product.sellingPrice), sourceCost: Number(product.sourcePrice || 0) };
  const requestedId = clean(input.variantId);
  let variant = requestedId ? variants.find((item) => item.id === requestedId) : null;
  if (!variant) { const parsed = parseEncodedVariant(input.variant); if (parsed) { const key = Object.keys(parsed.options).sort().map((k) => `${k.toLowerCase()}=${parsed.options[k].toLowerCase()}`).join("|"); variant = variants.find((item) => Object.keys(item.options).sort().map((k) => `${k.toLowerCase()}=${item.options[k].toLowerCase()}`).join("|") === key) || null; } }
  if (!variant) return { error: "Please select a valid product variant." };
  if (!isVariantInStock(variant)) return { error: "The selected variant is out of stock." };
  const sourcePrice = Number(variant.sourcePrice ?? variant.price ?? product.sourcePrice ?? 0);
  const selling = product.sourceSync?.pricingMode === "manual" ? Number(product.sellingPrice) : product.marginType === "percentage" ? sourcePrice * (1 + Number(product.marginValue || 0) / 100) : sourcePrice + Number(product.marginValue || 0);
  const unitPrice = Math.round(selling * 100) / 100;
  return { variant, selectedOptions: variant.options, unitPrice, sourceCost: sourcePrice };
}

export async function createResellingOrder(input: any) { await connectToDatabase(); const product = await ResellingProduct.findOne({ _id: input.productId, status: "published" }).lean() as any; if (!product) return { error: "Product not found or unavailable." }; const quantity = Number(input.quantity); const name = clean(input.customerName); const phone = clean(input.phone); const city = clean(input.city); const address = clean(input.address); if (!name || name.length > 100) return { error: "Enter a valid full name." }; if (!/^0[5-7][0-9]{8}$/.test(phone.replace(/[ .-]/g, ""))) return { error: "Enter a valid Moroccan phone number." }; if (!city || !address || !Number.isInteger(quantity) || quantity < 1 || quantity > 20) return { error: "Please complete the order form correctly." }; const resolved = resolveSubmittedVariant(product, input); if ("error" in resolved) return resolved; const normalizedPhone = phone.replace(/[ .-]/g, ""); const totalAmount = resolved.unitPrice * quantity; const sourceCostSnapshot = resolved.sourceCost * quantity; const profitSnapshot = Math.max(0, (resolved.unitPrice - resolved.sourceCost) * quantity); const orderNumber = `MT-${Date.now().toString(36).toUpperCase()}-${Math.floor(Math.random() * 900 + 100)}`; const variantSnapshot = resolved.variant ? { id: resolved.variant.id, options: resolved.variant.options, sourcePrice: resolved.variant.sourcePrice ?? resolved.variant.price ?? null, price: resolved.variant.price ?? null, stockStatus: resolved.variant.stockStatus ?? "unknown", stockQuantity: resolved.variant.stockQuantity ?? null, sku: resolved.variant.sku ?? null, sourceVariantId: resolved.variant.sourceVariantId ?? null } : null; const order = await ResellingOrder.create({ orderNumber, productId: product._id, productSnapshot: { title: product.title, mainImage: product.mainImage, sku: product.sku, sourceProvider: product.sourceProvider, sourceProductId: product.sourceProductId }, customerName: name, phone: normalizedPhone, city, address, quantity, variant: resolved.variant ? JSON.stringify({ id: resolved.variant.id, options: resolved.variant.options }) : "", variantId: resolved.variant?.id || "", selectedOptions: resolved.selectedOptions, variantSnapshot, customerNote: clean(input.customerNote).slice(0, 500), unitPrice: resolved.unitPrice, totalAmount, sourceCostSnapshot, profitSnapshot, paymentMethod: "cod", status: "pending" }); return { data: serializeDocument(order) }; }
