import { AdminMutationButton } from "@/components/admin-mutation-button";
import { StatusBadge } from "@/components/status-badge";
import { getAdminUsers } from "@/lib/admin";

export default async function AdminUsersPage({ searchParams }: { searchParams: Promise<{ role?: string; accountStatus?: string }> }) {
  const { role = "", accountStatus = "" } = await searchParams;
  const users = await getAdminUsers({ role: role || undefined, accountStatus: accountStatus || undefined });
  return <div className="space-y-8"><section className="rounded-[2rem] bg-white p-6 shadow-card"><h1 className="text-3xl font-black text-ink">Users</h1><p className="mt-3 text-sm text-ink/60">Manage registered accounts and platform access.</p><form className="mt-4 flex flex-wrap gap-3"><select name="role" defaultValue={role} className="rounded-xl border border-ink/10 px-4 py-2 text-sm"><option value="">All roles</option><option value="user">User</option><option value="agency">Agency</option><option value="renter">Renter</option><option value="admin">Admin</option></select><select name="accountStatus" defaultValue={accountStatus} className="rounded-xl border border-ink/10 px-4 py-2 text-sm"><option value="">All accounts</option><option value="active">Active</option><option value="disabled">Disabled</option></select><button className="rounded-full bg-forest px-4 py-2 text-sm font-semibold text-white">Filter</button></form></section><section className="grid gap-4">{users.map((user: any) => <article key={user._id} className="rounded-[2rem] bg-white p-6 shadow-card"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-xl font-bold text-ink">{user.name || "User"}</h2><p className="mt-2 text-sm text-ink/60">{user.email}</p><p className="mt-2 text-sm text-ink/60">Role: {user.role}</p><div className="mt-2"><StatusBadge kind="account" status={user.accountStatus} locale="fr" /></div></div><div className="flex flex-wrap gap-3">{["user", "agency", "renter", "admin"].map((nextRole) => <AdminMutationButton key={nextRole} endpoint={`/api/admin/users/${user._id}`} body={{ role: nextRole }} label={`Set ${nextRole} role`} variant={user.role === nextRole ? "neutral" : undefined} />)}<AdminMutationButton endpoint={`/api/admin/users/${user._id}`} body={{ accountStatus: user.accountStatus === "disabled" ? "active" : "disabled" }} label={user.accountStatus === "disabled" ? "Enable account" : "Disable account"} variant={user.accountStatus === "disabled" ? "neutral" : "danger"} /><AdminMutationButton endpoint={`/api/admin/users/${user._id}`} method="DELETE" label="Delete user" variant="danger" confirmText="Delete this user and related content?" /></div></div></article>)}</section></div>;
}
